### ISSUE TITLE
Awaited calls to Message.edit and Reaction.delete skipped without completing 

### ISSUE THREAD

**Issue by nebneb0703** [serenity-rs/serenity#1025]
Using version 0.9.0-rc.2

I am making an interactive game that updates the original message and waits for reactions. It works fine most of the time but seemingly randomly it just skips over the awaits.

I have put some debug printlns around my code and it seems to just completely skip past the message.edit and reaction.delete functions even though they are awaited, without actually removing the reaction and editing the message. The bot has permissions to do those, and it does work most of the time. I suspect it may have something to do with being rate limited?

I matched the result from those functions and they don't have the Err type when this happens, so I don't have any specific error message.

**Comment by Byter09** [comment]
Weird. I'm observing similar behaviour but with basic text messages. I also suspect rate limiting, but the weirdest thing I had yet to happen was that I got a response roughly 5 minutes later. Did this happen to you as well? Didn't want to open an issue for this because I thought my code just does something stupid, but your problem sounds exactly like mine.

**Comment by Lakelezz** [comment]
Can you please confirm this is still happening on the latest `0.9`?

Otherwise I will need to see your code please :)

**Comment by Lakelezz** [comment]
I will close this for now, if the problem persists with the latest `0.9`, please provide the related code!
