### ISSUE TITLE
Migrating generic command code from the 0.5 builder pattern to the attribute macro pattern

### ISSUE THREAD

**Issue by dgunay** [serenity-rs/serenity#1027]
Hi,

I am migrating code from v0.5 to v0.8 of Serenity and one pain point I'm experiencing is in translating code like this:

```rust
self.get_standard_framework()
            .command(Item::show(), |c| {
                c.bucket(bucket).exec(|_, m, a| search::<Item>(m, &a))
            })
            .command(Spell::show(), |c| {
                c.bucket(bucket).exec(|_, m, a| search::<Spell>(m, &a))
            })
            .command(Unit::show(), |c| {
                c.bucket(bucket).exec(|_, m, a| search::<Unit>(m, &a))
            })
            .command(Site::show(), |c| {
                c.bucket(bucket).exec(|_, m, a| search::<Site>(m, &a))
            })
            .command(Merc::show(), |c| {
                c.bucket(bucket).exec(|_, m, a| search::<Merc>(m, &a))
            })
            .command(Event::show(), |c| {
                c.bucket(bucket).exec(|_, m, a| search::<Event>(m, &a))
            })
```

... to using attribute macros. The old builder pattern code uses generics and traits to reuse the same function, but when I compile that generic function I get this error:

```
error: expected parentheses
  --> src/commands/search.rs:82:10
   |
82 | fn search<I: InspectorCategory>(message: &Message, args: &Args) -> Result<(), CommandError> {
```

I assume this is because the new macro command framework doesn't support generics. Is there a recommended way to work around this? I have been able to at least wrap these functions in new ones without generics, but it's a big loss in flexibility and I think some of the tests rely on generics to mock things out and I imagine those would not work with this approach.

Is there any way to integrate a generic function like this into the new macro command system?

**Comment by arqunis** [comment]
Generics aren't supported by the macros because during the design stage, it didn't make sense. Command functions and checks don't have generic parameters themselves, so the thought didn't cross my mind, but I can see how they're useful in this case.

As a compromise, you can retain the search function, define each of the commands individually, and call the function inside of their bodies. E.g..:
```rust
#[command]
pub fn item(ctx: &mut Context, msg: &Message, args: Args) -> CommandResult {
     search::<Item>(ctx, msg, args)
}
```
You'll have to do this for each function. However, at the very least, you can still reuse code in all of the commands.

Also, I saw your PR, and yes, [your usage of `CacheRwlock`/`CacheAndHttp` is wrong](https://github.com/djmcgill/dominions-5-status/blob/ac399238a404a9d71e18cb841dcee31c449490c5/src/commands/servers.rs#L136). Prior to 0.8, we had a global cache and http client, but this complicated initialization of the library and prevented users from running two or more bots in the same process. It also caused surprising behaviour, as depending on whether you had the `cache` feature enabled or not, functions may have acted differently. In 0.8, instances of the cache and http client are passed to the `Context`, and every function that worked on either the cache, http client, or both, were changed to accept those instances as their first argument. What you're supposed to do is pass a reference to the `Context` to those functions that expect a cache, http client, or both.

For example:
```rust
#[command]
pub fn ping(ctx: &mut Context, msg: &Message, args: Args) -> CommandResult {
    msg.channel_id.say(&ctx, "Pong!");
    // ----------------^^^^
    Ok(())
}
```

What you're doing is creating empty instances of the cache, which has no data, and the http client, which doesn't have a token, and passing them to the functions.

**Comment by dgunay** [comment]
Thanks for the help and advice. I think it probably won't be a big deal to just refactor the code to work with the new paradigm. I'll make sure to correct my usage of `CacheRwLock` and `CacheAndHttp`.
