### ISSUE TITLE
Feature specification when not using framework feature

### ISSUE THREAD

**Issue by casey** [serenity-rs/serenity#1052]
I'm using serenity without frameworks. Since this requires turning off default features, I have to copy the list of default features, without the `framework` and `standard_framework` features into my `Cargo.toml`:

```toml
[dependencies.serenity]
version = "0.9.0"
default-features = false
features = [
  "builder",
  "cache",
  "client",
  "gateway",
  "model",
  "http",
  "utils",
  "rustls_backend",
]
```

It seems like it's possible that my copy of the default features list will get out of sync with serenity's.

It might be nice to instead not include the `framework` and `standard_framework` features in the default feature set. This would allow users who prefer not to use frameworks to not have to turn off default features, and not have to copy the default feature set.

**Comment by Lakelezz** [comment]
Hello, glad to see interest in this topic.

Let me preface it with: Most people using Serenity use the standard framework, that's why it always has been a default. 

What can be done is offering a feature flag to include everything but the framework, for example `default_no_framework_rustls` and `default_no_framework_native_tsl`.

However do be aware, you should - in theory - always evaluate why you need a feature.
In your case, you may copy over all the features but what you actually do is copying over all the features you really need.
To quickly get started with bot development, default features are often plenty, but practically, you should always disable them and then handpick.
Which raises another question: Should we remove default features and motivate to pick features yourself providing a good guide on what one would need?

**Comment by casey** [comment]
That all makes sense. I personally like the way [sqlx](https://github.com/launchbadge/sqlx) does it. Some features, namely async runtime and TLS type need to be specified, and if you don't it's an error, and they [have a section in the docs](https://github.com/launchbadge/sqlx#install) explaining which features you need to choose from.

**Comment by Lakelezz** [comment]
We do have this here: https://github.com/serenity-rs/serenity#features
The TLS backend needs to be selected for Serenity as well, otherwise we error.

**Comment by casey** [comment]
Ah, I didn't see that. Thanks for pointing that out. I probably just should have read the docs more carefully :P
