### ISSUE TITLE
Context.set_activity doesn't always set the activity

### ISSUE THREAD

**Issue by techmccat** [serenity-rs/serenity#1104]
When set_activity is called more than once only the last one has an effect, when it's inside a loop it doesn't work at all.
For example the following impl block will set the activity to "Playing bar" after 5 seconds, but never "Playing foo"
```rust
impl EventHandler for Handler {
    async fn ready(&self, ctx: Context, ready: Ready) {
        ctx.set_activity(Activity::playing("foo")).await;
        sleep(Duration::from_secs(5));
        ctx.set_activity(Activity::playing("bar")).await;
    }
}
```
rustc 1.48.0 (7eac88abb 2020-11-16)
serenity 0.9.2

**Comment by arqunis** [comment]
The reason is because of the blocking `sleep` function in your code. 

`Context` acts as a messenger between you and the shard it was created from. `Context::set_activity` doesn't set the activity itself, it just sends a command to the shard to actually set a new activity, so it returns immediately once it has sent the command. The problem here is that you are mixing asynchronous and synchronous code*. 

To run a future (heart of `async`/`.await` in Rust) to completion, it needs a scheduler, but the scheduler (to be exact, `tokio`'s scheduler) gets blocked by the `sleep` function. This will not only block code you have in your `ready` handler, but everything relying on the scheduler, including Serenity itself. As a result, you will only see "Playing bar" because, while the previous set activity command will get processed eventually after the `sleep` function ends, it just gets immediately overridden by the new set activity command and that's what Discord will display in the end.

To fix this, use [tokio's `delay_for` function](https://docs.rs/tokio/0.2.23/tokio/time/fn.delay_for.html). It carries out the same task as `std::thread::sleep`, but doesn't block the scheduler.

Edit:
\* \- In case you misunderstand, I'm not stating you are not allowed to mix async and sync code, you just have to be wary of sync code that can block for a long time.
