### ISSUE TITLE
Interaction Create events cannot be deserialised properly

### ISSUE THREAD

**Issue by LavaToaster** [serenity-rs/serenity#1160]
I've had a stab at this myself, but I've been unable to figure out how to deal with this.

Take this json:

<details>
<summary>Sample JSON Payload</summary>

```
{
  "t": "INTERACTION_CREATE",
  "s": 6,
  "op": 0,
  "d": {
    "version": 1,
    "type": 2,
    "token": "",
    "member": {
      "user": {
        "username": "LavaToaster",
        "public_flags": 576,
        "id": "79640744414941184",
        "discriminator": "0001",
        "avatar": "4a1fdcbad2feb3356e329c1e1a306e1a"
      },
      "roles": [
        "551620810108960775"
      ],
      "premium_since": null,
      "permissions": "2147483647",
      "pending": false,
      "nick": null,
      "mute": false,
      "joined_at": "2017-02-28T17:01: 58.191000+00: 00",
      "is_pending": false,
      "deaf": false
    },
    "id": "793537274918207498",
    "guild_id": "286181213067280384",
    "data": {
      "name": "ping",
      "id": "793383598706262037"
    },
    "channel_id": "286181213067280384"
  }
}
```

</details>

If you receive it right now, it'll give back an error saying that it can't find `guild_id`. Cool because the incoming payload doesn't have `guild_id` on the member, but it expects one on the `Member` struct. You can work around this by making it a `PartialMember`, albeit that's a half solution IMO since you have more data available in this payload. Anyway, let's make that change and move on.

Next it then says gives an error:

```
Json(Error("invalid type: integer `2`, expected string or map", line: 0, column: 0))
```

Which is the `InteractionType` enum, and here's kind of where I've hit my blocker. I tried making the enum match others, such as `MessageActivityKind`, with the `enum_number!` and the implementation num thing, but that's been no bueno since when I do it, I get compile errors about lifetimes. So 🤷. 

Here's an issue, happy to sort it out myself if someone points me in the right direction.

**Comment by drklee3** [comment]
`guild_id` isn't provided by the API on the Member struct, so they're manually inserted in serenity.  Instead of deserializing the payload directly into the structs, you can first deserialize it as a `json::Value`, manually insert the `guild_id` in the Member map, then use `serde_json::from_value` to convert the Value to the Interaction struct.

An example:

https://github.com/serenity-rs/serenity/blob/7684323d1264583d8f3d0424bd8fca1e0abf1941/src/model/event.rs#L428-L443

Edit: This one probably more helpful

https://github.com/serenity-rs/serenity/blob/7684323d1264583d8f3d0424bd8fca1e0abf1941/src/model/event.rs#L588-L596
