### ISSUE TITLE
Reexport publicly exposed dependencies (e.g. parking_lot)

### ISSUE THREAD

**Issue by kangalio** [serenity-rs/serenity#1227]
Serenity exposes types of some dependencies as part of its public API, for example `parking_lot::RwLock` as `serenity::prelude::RwLock`. However, when interacting with those objects (for example `.read()` or `.write()`), it may yield types that serenity does not reexport, at which point you need to copy the dependency into your project Cargo.toml.

This is also unfortunate because serenity seems to bump its publicly exposed dependency versions even in PATCH updates, for example
- `serenity 0.8.6` -> `parking_lot 0.9`
- `serenity 0.8.9` -> `parking_lot 0.11`

So your project code will potentially break even on semver-compatible serenity updates.

Would it be possible to reexport the dependency in its entirety (`pub use parking_lot`)?

**Comment by Lakelezz** [comment]
Thank you for raising this issue.

The actual problem here is up'ing `parking_lot` to a breaking version on a stable Serenity series.
This should not happen, however there is not really a good way to fix this retroactively.

Nonetheless, while your suggestion is good, it seems like an unnecessary update for the `0.8`-series. It only receives bug fixes at this point, especially since it uses the old Discord gateway, therefore I would highly recommend upgrading to `0.10`. The entire asynchronous approach suits I/O heavy applications, such as bots, way more too.
