### ISSUE TITLE
reply_ping doesn't allow mentioning additional users

### ISSUE THREAD

**Issue by Samboy218** [serenity-rs/serenity#1236]
reply_ping does not allow mentioning users (other than the user being replied to) in the message body.

`
let msg_content = format!("Pinging other users: {} {} {}", user1.mention(), user2.mention(), user3.mention());
message.reply_ping(&ctx, msg_content).await;
`  

Expected result: 'message' is replied to with an inline reply with the content 'Pinging other users: @user1 @user2 @user3'
Actual behavior: 'message' is replied to with an inline reply but the extra mentions are broken (does not notify users, and on mobile the mentions appear as '@invalid_user'). if one of the extra mentions is of the user being replied to, that mention will actually work.

the user who is being replied to will be properly mentioned, but the additional mentions in the message body are blocked because reply_ping builds the message by setting allowed_mentions to only the replied user. 
see https://docs.rs/serenity/0.10.2/src/serenity/model/channel/message.rs.html#624

reply_ping is at
https://docs.rs/serenity/0.10.2/src/serenity/model/channel/message.rs.html#579

serenity version 0.10.2
rustc version 1.49.0

**Comment by Zaitara** [comment]
~~This has nothing to do with serenity, discord mobile displays uncached users as `@invalid_user`. Furthermore, discord does not allow inline reply to ping several people, as the purpose is only to ping the message author.~~

Thanks for the clarification kangalioo, I misunderstood.

**Comment by kangalio** [comment]
I can replicate this.

> This has nothing to do with serenity, discord mobile displays uncached users as `@invalid_user`

To be fair, Discord mobile _does_ show mentioned users correctly when something other than `reply_ping` is used (i.e. allowed_mentions is not set):
<img height=200 src="https://user-images.githubusercontent.com/21220820/119370423-8b790a00-bcb5-11eb-94dc-36f2b636e0a5.png">
[Screenshot from Discord mobile on the kangalioo account]

Though I agree that this is a bug/issue with Discord mobile. However, I believe this issue is less about the pecularities of `@invalid_user` on mobile than the fact that serenity's `reply_ping` sets allowed_mentions to only the replied user, for no clear reason.

> Furthermore, discord does not allow inline reply to ping several people, as the purpose is only to ping the message author.

This doesn't seem to be true. You can embed pings even in inline reply messages, and they will ping the user. See this image from the perspective of the `ooilagnak` account:
<img height=200 src="https://user-images.githubusercontent.com/21220820/119371002-3f7a9500-bcb6-11eb-9814-bc44c199a507.png">

Code to reproduce: https://pastebin.com/f3MtjP0z
