### ISSUE TITLE
Support for Public/Private Thread Channels

### ISSUE THREAD

**Issue by JellyWX** [serenity-rs/serenity#1270]
Not known exactly what these channels will be like yet since they seem pretty undocumented, but they use ChannelType 11 and 12 respectively.

Relevant:
https://twitter.com/advaithj1/status/1367292372128722944?s=20
https://github.com/discord/discord-api-docs/pull/2693

**Comment by boehs** [comment]
I reccomend editing this issue to be thread specific now. covering two scopes in one issue just nags me a little bit, especially now that Stage channels have been implemented and the only support needed is Threads - but this issue should not be closed due to the thread scope.

---

Rant aside, relevent documentation on threads is here: https://github.com/discord/discord-api-docs/blob/master/docs/topics/Threads.md and a PR covering this is https://github.com/discord/discord-api-docs/pull/2855. This should likely be implemented in a new branch as although the documentation is there threads are unusable.
