### ISSUE TITLE
Howto shutdown, exit, quit or teardown bot gracefully?

### ISSUE THREAD

**Issue by DartMen** [serenity-rs/serenity#1290]
I switched to another crate.

**Comment by arqunis** [comment]
Although you have switched to another crate, I'll attempt to answer this anyway:
The `Shard::shutdown_clean` method only turns off a single shard by severing the connection to Discord with a close code. If you had multiple shards active, it wouldn't cause the bot to quit entirely, as other shards would be still running. The reason the method doesn't quit the bot that has just one shard is due to the default behaviour of the shard runner. Its job is to maintain a connection to Discord for a shard for as long as possible, reconnecting and restarting it as is necessary. This includes cases where the shard had been asked to close its connection. The only situation when a shard can close for good is when its shard runner is discarded/removed.

The solution to gracefully quit a bot is with the [`ShardManager::shutdown_all`] method. That will cleanly shutdown all shards, removing their shard runners as well. You can [access the shard manager][access-client] from the client after you have initialised it. To access the shard manager from the event handler, however, you'll need to utilise the [`data`] field, which is present on the client and the context, and is shared between the two. You can make a copy of the `Arc` to the shard manager, insert it into the data field, and then access the manager from the data field with the context. [Example 6](https://github.com/serenity-rs/serenity/blob/current/examples/e06_sample_bot_structure/src/main.rs#L43) [showcases](https://github.com/serenity-rs/serenity/blob/current/examples/e06_sample_bot_structure/src/main.rs#L112-L115) [this](https://github.com/serenity-rs/serenity/blob/current/examples/e06_sample_bot_structure/src/commands/owner.rs#L11).

[`ShardManager::shutdown_all`]: https://docs.rs/serenity/0.10.5/serenity/client/bridge/gateway/struct.ShardManager.html#method.shutdown_all
[access-client]: https://docs.rs/serenity/0.10.5/serenity/client/struct.Client.html#structfield.shard_manager
[`data`]: https://docs.rs/serenity/0.10.5/serenity/client/struct.Client.html#structfield.data
