### ISSUE TITLE
Getting Channel via Channel Name

### ISSUE THREAD

**Issue by Selyatin** [serenity-rs/serenity#1376]
Is there a way to get a channel without looping through the entire channel map of the guild?

Right now I'm doing something like this

```rust
let channels = guild_id.channels(context).await;

for (_, channel) in channels {
   if channel.name(context).await.unwrap_or("".to_owned()) != "general" {
       continue;
   }
}
```

Is there a way to just get a channel via it's name or fail without all these loops? Maybe I'm missing something?

**Comment by kangalio** [comment]
Guild has a method `Guild::channel_id_from_name`. You only seem to have a GuildId available, so you would need to call `guild_id.to_guild_cached` first.

Guilds should be in cache as long as the cache feature is enabled and your bot is a member of the guild.

Alternatively, you could slightly shorten your existing code using iterator methods:
```rust
let channels = guild_id.channels(context).await;
if let (_, general) = channels.iter().find(|(_, channel)| channel.name.as_deref() == Some("general")) {
    // ...
}
```
(untested since I'm on mobile)

**Comment by Selyatin** [comment]
Oh, I might be able to optimise this even further by using the `guild_field` function from the cache, so that I won't have to clone the entire guild data, I'll be back once I try it.

**Comment by Selyatin** [comment]
I went with the iterator method, thanks!
