### ISSUE TITLE
The trait `CacheHttp` is not implemented for `Cache`

### ISSUE THREAD

**Issue by tiritto** [serenity-rs/serenity#1514]
**Affected branch:** `Next`

As the title says, during compilation I get the following error:
> error[E0277]: the trait bound `Cache: CacheHttp` is not satisfied
```
let test = msg.channel(*ctx.cache).await;
                       ^^^^^^^^^^ the trait `CacheHttp` is not implemented for `Cache`
```

This appears to be either a bug or mistake in the documentation itself, since according to the documentation:
> The types Context, Cache, and Http implement this trait and thus passing these to functions expecting impl CacheHttp is possible.

**Related code fragment:**
```rust
async fn message(&self, ctx: Context, msg: Message) {
     let test = msg.channel(*ctx.cache).await;
}
```
The same issue happens when I try to pass `ctx.cache` without dereferencing it, as `Arc<Cache>`, which I assume is also a bug, since `Arc<Http>` can be passed over as atomic reference just fine. 

For the sake of clarity, I will mention that using `&ctx` alone in the same use case is working just fine, which would make this issue rather low priority.

**The following code works as intended:**
```rust
async fn message(&self, ctx: Context, msg: Message) {
     let test = msg.channel(&ctx).await;
}
```

**Comment by arqunis** [comment]
Indeed, the phrasing of the documentation is a bit wrong, but it's not entirely invalid. We should emphasise the first sentence of the documentation for `CacheHttp`, because it describes the reason for the existence of trait:
> This trait will be required by functions that need Http and can optionally use a Cache to potentially avoid REST-requests.

A lot of model structs offer methods to modify their state, by, for example, making a HTTP request to add, change, or delete a channel, or to retrieve information from Discord's API, again by making a HTTP request. At the very least, these methods require access to an instance of the `Http` client. Most of the time, however, it would be beneficial to reduce the amount of requests to Discord's API, when, for instance, retrieving member data. This is where the `Cache` plays the role. It it used to increase performance and lessen load on the network by temporarily caching data from Discord. But, unlike the `Http` client, the `Cache` is optional. A user is not obligated to pass it to every method like they have to with the `Http` client, nor do they have to compile support for it (it can be disabled/enabled with the `cache` feature).

It is for that reason that we have devised `CacheHttp`: to give users a choice, so that they may pass just the `Http` client, or a combo of the `Http` client and the `Cache`. The trait is not for situations where the `Cache` is the only utility needed for a model method. Therefore, the fact that your snippet with `msg.channel(*ctx.cache)` (or `msg.channel(&ctx.cache)`) doesn't compile is intentional. 

Although, I do concede that the line about implementing `Cache` should be adjusted. `CacheHttp` doesn't implement it directly, but indirectly through a grouping, like with a struct (`Context`, which contains `Arc` references to the `Http` client and the `Cache`; or `Arc<CacheAndHttp>`), or a tuple (`(&Arc<Cache>, &Http)`).
