### ISSUE TITLE
How do I lookup a user by user id? What is `(CacheRwLock, Http)`?

### ISSUE THREAD

**Issue by chrissound** [serenity-rs/serenity#1557]
```rust
use serenity::model::id::GuildId;
use serenity::model::voice::VoiceState;
use serenity::model::id::ChannelId;
use serenity::model::user::User;
use serenity::model::id::UserId;

async fn woo(user : u64, &p : &u64) -> String {
    println!("User you're following is online!");

    let vvv = UserId(p).to_user((CacheRwLock, Http));

    let response = MessageBuilder::new()
        .push("User is active in voice chat!")
        .user(vvv.name)
        .build();

    return response;

}
```

I'm assuming I should use the `to_user()` function above for this purpose, however I'm not sure what `(CacheRwLock, Http)` refers to as stated in the docs https://github.com/serenity-rs/serenity/blob/b21f053b87d611d0f803cdfbc232b70621daa3ab/src/http/mod.rs#L67?

**Comment by arqunis** [comment]
To retrieve an instance of a `User` by ID, then yes, `UserId::to_user` is the correct method. However, it cannot conceive the `User` data out of nothing, it has to get it from somewhere. `UserId::to_user` may use the HTTP client to make a request to Discord's API in order to fetch the data, or it may use the cache, which stores data received via Discord's gateway. Either of these (or both) have to be passed as a parameter to the method for it to work. We use the `CacheHttp` trait to support this. 

The `(CacheRwLock, Http)` type that you note (which should actually be `(&Arc<Cache>, &Http)` in the documentation) implements this trait, which means you can pass it as a parameter to `UserId::to_user` (or any other method that accepts `CacheHttp`). However, I would recommend to use the `Context` type instead. It also implements `CacheHttp`, and you should already have an instance of it if you are calling `woo` from an event handler function or command.

```rust
async fn woo(ctx: &Context, user: u64, &p: &u64) -> String {
    println!("User you're following is online!");

    let vvv = UserId(p)
        .to_user(ctx)
        .await
        .expect("failed to retrieve user");

    // By the way, the last expression of a function body gets automatically returned
    // from the function (note that it must not be terminated by a semicolon).
    MessageBuilder::new()
        .push("User is active in voice chat!")
        .user(vvv.name)
        .build()
}
