### ISSUE TITLE
Support Context Menu Commands

### ISSUE THREAD

**Issue by Chronophylos** [serenity-rs/serenity#1610]
Application Commands can now be invoked from a context menu by setting the type of a command: https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-types

**Comment by kangalio** [comment]
They're supported (https://serenity-rs.github.io/serenity/current/serenity/model/interactions/application_command/enum.ApplicationCommandType.html), but there hasn't been a crates.io release since then.

If you want context menu command support, you can use a git dependency to the `current` branch for the time being

**Comment by Chronophylos** [comment]
Thank you, I'll do that
