### ISSUE TITLE
Adopt an Error handling method similar to Actix for Events

### ISSUE THREAD

**Issue by wyatt-herkamp** [serenity-rs/serenity#1644]
Inside Actix you can implement ResponseError on your Error and Actix will call this method if an Error occurs. https://actix.rs/docs/errors/

My example trait would be 
```rust
pub trait EventError {
    /// The event type would need to be changed
    async fn handle_error(self, context: &Context, event: &Event);
}
```

Inside these traits I would be able to call maybe reply to message "An Internal Error Has Occurred" And I also have an Error Logging Channel on this server to where I send the actual error so I can debug the problem. 

What do you do if an error occurs in these methods? Honestly, I do not really know. This only would be an issue if the Error was like an connection to Discord error or bad code. The first one being handled by logging in the console for the admin to figure out later.

**Comment by wyatt-herkamp** [comment]
P.S both traits would need a reference to &self

**Comment by kangalio** [comment]
Is this referring to errors in standard_framework commands, or errors in EventHandler functions?

**Comment by wyatt-herkamp** [comment]
> Is this referring to errors in standard\_framework commands, or errors in EventHandler functions?

I haven't touched Serenity in over a year now.   
  
But both. You should be able to define your own Error type and return it on commands and events.

**Comment by kangalio** [comment]
Alright. Custom error types in standard_framework commands is not going to happen, because development effectively stopped and its [successor](https://github.com/serenity-rs/poise/) already supports custom error types and a central on_error callback.

But custom errors in EventHandler could theoretically be implemented, at the cost of breaking all existing usages of EventHandler.

I feel like it's not worth it, because I think the future of handling arbitrary events is not EventHandler but a central callback with a [`FullEvent`](https://serenity-rs.github.io/serenity/next/serenity/client/enum.FullEvent.html) parameter, like [in poise](https://docs.rs/poise/latest/poise/structs/struct.FrameworkOptions.html#structfield.event_handler). By centralizing the callback, passing auxiliary data or handling errors in a centralized way becomes much easier

**Comment by wyatt-herkamp** [comment]
> Alright. Custom error types in standard_framework commands is not going to happen, because development effectively stopped and its [successor](https://github.com/serenity-rs/poise/) already supports custom error types and a central on_error callback.

Ok cool. I did not know that. As I mentioned I haven't played with Serenity in awhile. 

> But custom errors in EventHandler could theoretically be implemented, at the cost of breaking all existing usages of EventHandler.
> 
> I feel like it's not worth it, because I think the future of handling arbitrary events is not EventHandler but a central callback with a [`FullEvent`](https://serenity-rs.github.io/serenity/next/serenity/client/enum.FullEvent.html) parameter, like [in poise](https://docs.rs/poise/latest/poise/structs/struct.FrameworkOptions.html#structfield.event_handler). By centralizing the callback, passing auxiliary data or handling errors in a centralized way becomes much easier

Ok sounds good

**Comment by arqunis** [comment]
We have deprecated the standard framework and are moving towards [poise](https://github.com/serenity-rs/poise/) being the go-to framework instead.
