### ISSUE TITLE
Deserialization fails when struct includes any of the id types

### ISSUE THREAD

**Issue by LimitLost** [serenity-rs/serenity#1653]
Error: "invalid type: sequence, expected identifier"

Id types which I'm talking about: 
- `model::id::GuildId`
- `model::id::UserId`

I think this can be simply fixed by deriving default Deserialize provided by serde, since those types some custom one which breaks

**Comment by arqunis** [comment]
The error does not suggest to me that it is the fault of the ID types. What is your JSON input? It appears to be trying to deserialize from a sequence (array in JSON) to an ID, which is invalid. The `Deserialize` implementations on the ID types are written to deserialize from either:
- an integer
- a string
- a string in an object (this is a `serde_json` implementation detail)

And concerning your idea, `#[derive(Deserialize)]` wouldn't solve this, since [the implementation would still expect an integer, not a sequence](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a27c783f026cec8d97fd657af2ca5107).

**Comment by LimitLost** [comment]
Ok, then I created simple way to recreate this error (I'm using ron not json and default serde Serialize implementation serializes those id's as a structs with single value which suggests where the bug is):

cargo.toml:
```
[package]
name = "serenity_test"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = {version = "0.10.9", features = ["client", "gateway", "rustls_backend", "model", "unstable_discord_api","cache","collector"], default-features = false }

serde = "1.0.132"
ron = "0.7.0"
```
main.rs:
```
use serenity::model::id::UserId;

fn main() {

    let id= UserId(000000000);

    let ser=ron::to_string(&id).unwrap();

    let de:UserId=ron::from_str(&ser).unwrap();

    assert_eq!(id,de)
}
```
full error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Message("invalid type: sequence, expected identifier"), position: Position { line: 0, col: 
0 } }', src\main.rs:9:39
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:517
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\core\src\panicking.rs:101
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\core\src\result.rs:1617
   3: enum$<core::result::Result<serenity::model::id::UserId,ron::error::Error> >::unwrap<serenity::model::id::UserId,ron::error::Error>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\result.rs:1299
   4: serenity_test::main
             at .\src\main.rs:9
   5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\ops\function.rs:227
```

**Comment by arqunis** [comment]
> I'm using ron

I see. You should have specified this information beforehand. After running your code, I can realize where the issue is, and it is due to how `ron` handles tuple structs during serialization.

Serenity is a Discord API wrapper crate, which means we primarily communicate with the API through JSON. We use `serde_json` for serializing/deserializing JSON data. In regards to tuple structs, if it contains just one field, `serde_json` will emit the field directly when serializing, otherwise if the tuple struct has more than one field, it will emit the fields in an array. That is to say, this:
```rs
#[derive(Serialize)]
struct Foo(u64);
```
will generate
```json
// Foo(1)
1
```
while
```rs
#[derive(Serialize)]
struct Foo(u64, u64);
```
will generate
```json
// Foo(1, 3)
[1, 3]
```
instead.

However, `ron` seems to not care how many fields the tuple struct has and will always emit an array. That is, these:
```rs
#[derive(Serialize)]
struct Foo(u64);

#[derive(Serialize)]
struct Bar(u64, u64);
```
will always be generated as arrays
```ron
// Foo(2)
(2)
// Bar(4, 6)
(4, 6)
```

This is why you are getting the `invalid type: sequence, expected identifier` error, and why we hadn't encountered it thus far, since we only tested `Serialize` and `Deserialize` implementations with `serde_json`.

**Comment by nickelc** [comment]
Can you test it with the `next` branch?

```toml
[dependencies]
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }
```

**Comment by LimitLost** [comment]
> Can you test it with the `next` branch?
> 
> ```toml
> [dependencies]
> serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }
> ```

Done, this problem seems to be fixed in this branch.
