### ISSUE TITLE
Error downcasting in the `after` hook.

### ISSUE THREAD

**Issue by AlterionX** [serenity-rs/serenity#1735]
I might be missing something super obvious since I haven't really used serenity for that long, but it would be nice to support error downcasting in the `after` hook so that I don't need to do something like this:
```rs
#[hook]
pub async handle_errors(ctx: &Context, msg: &Message, command_name: &str, error: Result<(), CommandError>) {
    if let Err(e) = error {
        let more_errors = if e.description() == "some long string that has no chance of showing up in another error message because randomness" {
            // do something dangerous like
            let e = unsafe { &*(Box::leak(e) as *const Error as usize as *const MyError) };
            // or
            let e = unsafe { std::mem::transmute(e) };
            // proceed to handle custom error
            e.do_the_thing(ctx, msg).await;
        } else {
            util::request_support(ctx, msg).await;
        };
        // Handle the new error
    }
}
```
If there's a better way, please let me know. I tried looking for examples of this in the examples and issues, but couldn't really find any, so I'm wondering if I'm using the wrong tool for the job or there's an obvious answer I'm missing. (I swear, though, if someone says to create a custom framework...)

On the other hand, if there isn't a better way, I propose two possible ways to facilitate this:
1) adopting an error type parameter on `StandardFramework`. This type parameter would represent what kind of error its commands are expected to return and would default to CommandError. I understand this would be a pervasive change, but if done properly should have no impact on current users.
2) adding `Any` as a trait required from `CommandResult`'s boxed errors. ... I don't like this solution. Sidenote: solution 1 would allow me to monkey patch this in, anyways. Sidenote 2:  This is likely what I'll do for now, but I'd like to avoid maintaining a fork with just this as the change.

**Comment by AlterionX** [comment]
Sidenote: I'm doing this because the burdens of handling every error at site of error with a custom message to the user explaining what they did wrong and how to fix it is starting to become a severe overhead cost. So I'm looking to centralize that logic.

**Comment by arqunis** [comment]
> 2. adding `Any` as a trait required from `CommandResult`'s boxed errors. ... I don't like this solution. Sidenote: solution 1 would allow me to monkey patch this in, anyways.

No need. The `std::error::Error` trait supports downcasting the same way as `Any` does. The method that enables the functionality [is hidden from documentation](https://doc.rust-lang.org/stable/src/std/error.rs.html#118-123), but it is what `Any` relies on to distinguish types at runtime, even if their information has been lost at compile time.

To do downcasting safely, you need a piece of data that is unique to a type. The compiler fortunately provides this in the form of a `TypeId`, an identifier referring to a specific type. We can always retrieve a `TypeId` using its generic `of` method, which is what the hidden `type_id` method of `Error` (and `Any`) depends on.

Anyway, you can use one of the `downcast` methods found here: https://doc.rust-lang.org/stable/std/error/trait.Error.html#implementations. The most relevant being this one: https://doc.rust-lang.org/stable/std/error/trait.Error.html#method.downcast-2, as it allows casting a `Box<dyn std::error::Error + Send + Sync>` to a concrete, for instance, `Box<std::io::Error>`, without touching the allocation of `Box`. Of course, you may use `downcast_ref` or `downcast_mut` if all you care about is access to an error, rather than its ownership.

**Comment by arqunis** [comment]
```rust
#[hook]
pub async handle_errors(ctx: &Context, msg: &Message, command_name: &str, error: Result<(), CommandError>) {
    if let Err(e) = error {
        let more_errors = if let Some(e) = e.downcast_ref::<MyError>() {
            e.do_the_thing(ctx, msg).await
        } else {
            util::request_support(ctx, msg).await
        };
        // Handle the new error
    }
}
```

Here is your example rewritten to use `downcast_ref`.

**Comment by AlterionX** [comment]
Cool, and thanks! Will take a deeper look at Error.

Anyways, is there any chance a mention of this can get added to the docs for the `after` function for `StandardFramework`? Might be common knowledge for error handling, but it would still be helpful for anyone who doesn't know (like me, lol) and for whom this is the first time they're really encountering the `Error` trait.

**Comment by arqunis** [comment]
We have deprecated the standard framework and are moving towards [poise](https://github.com/serenity-rs/poise/) being the go-to framework instead.
