### ISSUE TITLE
Message crosspost permission missing in docs

### ISSUE THREAD

**Issue by FlareFlo** [serenity-rs/serenity#1761]
It appears that the `model::channel::Message` crosspost-function misses the required permission `Manage Channels`, as not granting it returns HTTP 403 with the error-id 50001.

**Comment by kangalio** [comment]
[edited; I misread the issue]

**Comment by kangalio** [comment]
Unfortunately I can't verify the claim, because I'm not admin of a guild with Community Servers enabled, but according [to Discord docs](https://discord.com/developers/docs/resources/channel#crosspost-message), only Manage Messages is required, not Manage Channels:
![image](https://user-images.githubusercontent.com/21220820/190826649-938bdb3e-7544-487a-b59f-7d7e40d43923.png)

**Comment by FlareFlo** [comment]
> Unfortunately I can't verify the claim, because I'm not admin of a guild with Community Servers enabled

I will re-validate that claim, considering the time that has passed.

**Comment by FlareFlo** [comment]
Cannot reproduce anymore :(

**Comment by kangalio** [comment]
No: cannot reproduce anymore :)

One less issue to be fixed :+1:
