### ISSUE TITLE
cache and msg.is_own()

### ISSUE THREAD

**Issue by Nogamara** [serenity-rs/serenity#1953]
Apologies, this is not a bug report (maybe docs or feature request).

I upgraded serenity from a very old (2018ish) version to 0.11 and I had to change this code:

```
- use serenity::CACHE;
[...]
- if msg.author.id == CACHE.read().unwrap().user.id {
+ if msg.is_own(&context.cache) {
```

Long story short, I tried to make sense of the docs and source and I found no easier way to discern if the currently received message was sent by the bot itself than using `cache` because even the old version didn't feel right to me.

Now quoting the cache docs:

> If you’re asking this, the answer is likely “definitely yes” or “definitely no”; any in-between tends to be “yes”. If you are low on RAM, and need to run on only a couple MB, then the answer is “definitely no”.

So my actual question is more like: Am I just not looking at the right place? Because surely for this simple thing (is this my own message?) I shouldn't have to enable the cache?

The only thing in the examples I found would be `ready.user.name|id` from the `Handler::ready` callback, but is that the intended way to check this? And following up, wouldn't that be good to add to the basic example?

**Comment by kangalio** [comment]
@Nogamara #2210 has been merged, which allows configuring the cache to take just a small fixed size.

Is it viable for you to enable the cache feature but disable the memory hungry cache features? That way, you still have all features available that rely on trivial data caching, like the current user ID, with the cache only taking away minimal additional amount of memory

**Comment by Nogamara** [comment]
Thanks @kangalioo - I'm not actually using my bot at the moment but I'll see if I can check it out and will give feedback if I see something.

Maybe I phrased my original ticket badly, but I'm still actively questioning whether using this cache feature makes sense at all if I just want to check "is this my own message, me the bot written in serenity", e.g. when only reacting to others' messages, when writing even the most basic echo bot that should not speak to itself without stopping.

My personal situation didn't make using the cache not feasible because it's too big or something, and I'm also not saying my 2018 code was good - merely that I probably even back then didn't find an easy way to check if the message was sent by the client running the serenity code in question

**Comment by kangalio** [comment]
Seems like serenity's usage of the term "cache" is misleading you. Serenity's cache is really just a storage for useful data received from Discord. The bot's user ID is also sent to the bot from Discord on startup - hence it goes into the "cache".

**Comment by Nogamara** [comment]
Good point, I just don't see any scenario where it would be useful to discard that info in this special case of n=1, cache or not. Cf the Handler::ready callback I mentioned.

But as I wrote originally, maybe this is confusing more people (with the former heavy discouragement of the cache and all), I'm not trying to argue.

**Comment by kangalio** [comment]
I understand your view point. Indeed, #2138 keeps current user data received from gateway, independent from the cache feature. But it didn't really work out, because all the infrastructure for storing gateway-received data is already centralized in the cache infrastructure. It was a big mess to implement.

So I thought about it and the sole reason people disabled the cache infrastructure was to save on memory. So I submitted #2210, which makes the cache configurable at runtime. With that, the main reason for disabling the cache infrastructure at compile time is gone.

Now, you can enable the `cache` feature but disable the actual caching capabilities. This will only store the current user data and not more, thereby still enabling you to use cache-gated methods such as is_own.

Therefore, I'll close the issue. If there is something left to do after all, I'll reopen
