### ISSUE TITLE
MessageCreateEvent doesn't have message content

### ISSUE THREAD

**Issue by glcraft** [serenity-rs/serenity#2053]
I just find a weird behaviour, I don't know if it is intended or if it's a bug :

When I receive a MessageCreate event, i have all informations about that message but the content.

![image](https://user-images.githubusercontent.com/6421451/179356923-89c38df7-1b02-42bc-833f-48709aeaa68f.png)

To test if my intents were not well configured or anything else, I tried to download the message with `ChannelId::message()`. Then I got the content : 

![image](https://user-images.githubusercontent.com/6421451/179356947-01955a86-9ff8-4c5c-891e-a6b16f74bb56.png)

Is it normal that i can't have the content in the event but I can have it when i call `ChannelId::message()` ?

**Comment by arqunis** [comment]
Did you enable the privileged intent for message content in your bot's developer page and supply [the `MESSAGE_CONTENT` intent](https://serenity-rs.github.io/serenity/current/serenity/model/gateway/struct.GatewayIntents.html#associatedconstant.MESSAGE_CONTENT) to the [`Client`](https://serenity-rs.github.io/serenity/current/serenity/client/struct.Client.html#method.builder)?
![image](https://user-images.githubusercontent.com/16745149/179357103-079723c7-888e-4e17-9292-5c9f0cfff9a8.png)

This is not a bug, it is intentional on Discord's part to protect people from bots reading their messages unauthorised. You may perform the steps I described to access content of messages received via the gateway, but if your bot is in more than a 100 servers, you'll need Discord's approval to be able to read the content afterwards.

**Comment by glcraft** [comment]
@acdenisSK yes i did, as you can see here :
![image](https://user-images.githubusercontent.com/6421451/179370167-c32d5a89-62e6-4b71-ba44-0ab1b25830c5.png)

My bot is on only one server. And I'm able to download the content by using ChannelId::message(msg_id), which also requires message content intent.

**Comment by arqunis** [comment]
@glcraft Your screenshot shows the `GUILD_MEMBERS` intent, which is separate from the `MESSAGE_CONTENT` intent. And I must mention again, enabling it in the developer portal is not enough, you also have to specify the intent when building the `Client`.

**Comment by glcraft** [comment]
oops i'm sorry, i did not screenshot the good option. It is also enabled.

> And I must mention again, enabling it in the developer portal is not enough, you also have to specify the intent when building the Client.

Oh... That was that simple, I'm a bit ashamed 😅
Thank you for the answer, it works like a charm now 👍
