### ISSUE TITLE
ReactionType does not implement Mentionable and does not have conversions to EmojiIdentifier (which does)

### ISSUE THREAD

**Issue by FichteFoll** [serenity-rs/serenity#2066]
As far as I can see, refrencing a ReactionType in a message currently requires to either implement the formatting manually (via `format!`) or to manually convert to a EmojiIdentifier which then implements `Mentionable`  (and you'd just use the verbatim string for the `Unicode` case).

Imho implementing `Mentionable` for ReactionType makes sense here.

**Comment by kangalio** [comment]
ReactionType implements Display, so you can print it directly: `format!("Emoji: {}", reaction_type)`

I've had a look at ReactionType, EmojiIdentifier, Mentionable and Mention. I believe implementing Mentionable on ReactionType doesn't make sense. Mention seems to be only for Discord's `<...>` type mentions. Custom emojis are part of that, hence EmojiIdentifier implements Mentionable (even that is borderline imo because posting an emoji is not a mention). But ReactionType support both custom and Unicode emojis (that's also why you can't directly convert it to EmojIdentifier, which is custom only), and Unicode emojis definitely don't fit the Mention type.

**Comment by FichteFoll** [comment]
Thanks for the reply. I belive I understand where my confusion is coming from. There is indeed an exact implementation for what I was looking for in [`impl Display for ReactionType`](https://docs.rs/serenity/0.11.5/src/serenity/model/channel/reaction.rs.html#653), but I didn't find it in the documentation whereas I did find it in `mention` for `EmojiIdentifier`, so I believed it was missing for ReactionType and ended up [reimplementing it](https://github.com/Infiziert90/Reaction-Toplist-Bot/blob/47efc3bc06f9fa65a3cf2398bb2205c6df32f3d3/src/main.rs#L260-L271). Using the Display implementation is definitely fine for my use case.

In order to potentially reduce confusion for others, maybe `EmojiIdentifier` and `Emoji` shouldn't implement `Mentionable` either because using an emoji in a chat message is, as you said, not actually a "mention"? (Just like using the custom datetime formatting isn't.)

**Comment by kangalio** [comment]
Can be closed
