### ISSUE TITLE
Add support for Forum Tags

### ISSUE THREAD

**Issue by Chronophylos** [serenity-rs/serenity#2292]
I want to:
- add tags when creating a new post (thread): https://discord.com/developers/docs/resources/channel#start-thread-in-forum-channel
- get tags in a forum and thread: https://discord.com/developers/docs/resources/channel#channel-object
- edit tags in a forum: https://discord.com/developers/docs/resources/channel#modify-channel-json-params-guild-channel
- edit tags in a post (thread): https://discord.com/developers/docs/resources/channel#modify-channel-json-params-thread

The fields `available_tags` and `applied_tags` are missing in a couple of models, some functions need to be added to `EditChannel` and `EditThread`, and a new `Tag` model is required.

See also https://discord.com/developers/docs/resources/channel#forum-tag-object

**Comment by kangalio** [comment]
1. Has been implemented: [`CreateForumPost.add_applied_tag()`](https://serenity-rs.github.io/serenity/next/serenity/builder/struct.CreateForumPost.html#method.add_applied_tag)
2. Has been implemented: [`GuildChannel.available_tags`](https://serenity-rs.github.io/serenity/next/serenity/model/channel/struct.GuildChannel.html#structfield.available_tags), [`GuildChannel.applies_tags`](https://serenity-rs.github.io/serenity/next/serenity/model/channel/struct.GuildChannel.html#structfield.applied_tags)
3. **Not implemented** (no `edit_available_tags` in [`EditChannel`](https://serenity-rs.github.io/serenity/next/serenity/builder/struct.EditChannel.html) yet)
4.  **Not implemented** (no `edit_applied_tags` in [`EditThread`](https://serenity-rs.github.io/serenity/next/serenity/builder/struct.EditThread.html) yet)

I'd like to (implement and) test 3 & 4, but forums are restricted to community servers and I don't have access to one with permission to create a testing forum channel.

Is there an admin of a community server that would be willing to let me create one test forum channel to implement this PR? Otherwise, maybe someone else can implement the PR themselves

**Comment by rlnt** [comment]
@kangalio I can provide you with a server. Hit me up on Discord Relentless#3812
