### ISSUE TITLE
How to modal?

### ISSUE THREAD

**Issue by aalhitennf** [serenity-rs/serenity#2312]
How do i create modal with text inputs?  

```
    let m = msg
        .channel_id
        .send_message(&ctx, |m| {
            m.content("Please select what ever")
                .components(|c| {
                    c.create_action_row(|row| {
                        row.create_input_text(|text| {
                            text.custom_id("test");
                            text.label("test");
                            text.placeholder("test");
                            text.style(InputTextStyle::Short);
                            text.value("test")
                        });
                    c.create_action_row(|row| {
                        row.create_button(|btn| {
                            btn.custom_id("send_btn");
                            btn.label("Send")
                        })
                    })
              })
        })
        .await
        .unwrap();

    let interaction = match m
        .await_modal_interaction(ctx)
        .timeout(Duration::from_secs(60 * 3))
        .await
    {
        Some(x) => x,
        None => {
            m.reply(&ctx, "Timed out").await.unwrap();
            return Ok(());
        }
    };
```

Thats what i currently have but i get error `Value of field \"type\" must be one of (2, 3, 5, 6, 7, 8).", path: "components.0.components.0"`, and i cant find a way to set that type to anything.

**Comment by aalhitennf** [comment]
nvm me stupid

**Comment by SUPERetnad01** [comment]
I guess I am stupid, I don't know how to get a modal to appear. From the discord docs I get that you can't use text fields in a component, but I don't know where to set the text_input_fields

**Comment by rwdj** [comment]
@SUPERetnad01
It appears `InputText` is type 4, which their error message says is invalid. It doesn't seem modals are stable, because I'm getting the exact opposite of this person: `Value of field "type" must be one of (4,).` That means InputText is the only valid type. Same happens if I add another action row (data.components.0.components.1),

As far as I can tell, this comes from: https://github.com/serenity-rs/serenity/blob/9fc3f1180ddee5526a78c6e72deaaa9dd7be1f03/src/builder/create_components.rs#L450
But I notice this file is very different in the "next" branch, so there's probably extensive work going on for this. So maybe it'll get better.

**Comment by SUPERetnad01** [comment]
@rwdj I am very curious what your code is. I am almost doing the same as the answer above.
