### ISSUE TITLE
Implement `Deserialize` on all builder types

### ISSUE THREAD

**Issue by AngelOnFira** [serenity-rs/serenity#2324]
As I've been looking through types in the builder on the `next` branch, it seems that many are `Serialize`, but few are `Deserialize`. I'm hoping to have both traits implemented, as so I can store builders in my database to be used later. [For example](https://github.com/serenity-rs/serenity/blob/72c76467dab136f50c2b1739e1945736e4a7ff39/src/builder/create_components.rs#L151):

```rust
/// A builder for creating a [`SelectMenu`].
///
/// [`SelectMenu`]: crate::model::application::SelectMenu
#[derive(Clone, Debug, Serialize)]
#[must_use]
pub struct CreateSelectMenu {
  ...
}
```

I'm curious about what complications lie in just adding `Deserialize`? (Other than having to do it on any sub types).

**Comment by AngelOnFira** [comment]
Also, if there are no large blockers on this, I wouldn't mind going through and setting this up best I can :)

**Comment by AngelOnFira** [comment]
I made this commit on my fork so that I could get things working locally, and it *seems* to work on a surface level. Though I don't know if there are other footguns, since I've never really fooled around with Serde past the derive traits.

Commit link: https://github.com/AngelOnFira/serenity/commit/a7600e565240a9b520109ac34cb3334be337892b

**Comment by kangalio** [comment]
Status: we need feedback from those users who'd like to store and load builders locally, in order to devise an alternative approach. What's your use case? If you could turn builder structs into a generic `Request` struct that could be stored locally and executed later, would that work for you?

(Using the existing Serialize impls is problematic because they are tuned specifically for the Discord API, and hence leave out some fields of the serialized payload (bad!) or require special formatting which would have to be replicated in the Deserialize impl (annoying!))

(this message was copied from the linked PR)

**Comment by GnomedDev** [comment]
This is a bad idea, this is the same as making all builder fields public on a semver point of view. Let's not.
