### ISSUE TITLE
Possible to use this with user account instead of bot account?

### ISSUE THREAD

**Issue by gohanko** [serenity-rs/serenity#2410]
I have a use case where I want to write an application that automatically delete all my message in a server. Would it be possible to use this library in such use case without the account getting banned?

**Comment by kangalio** [comment]
Serenity does not support this natively because Discord doesn't allow third-party API wrappers to support user accounts.

You can probably edit the serenity code to patch support back in, but I have no idea how that works and how much effort it is.

Whether the account will be banned is solely dependent on how sharp-eyed Discord TOS breaking detection is. From what I've heard, it's pretty lenient

**Comment by gohanko** [comment]
From what I understand, as long as you do not behave like a bot using a user account (i.e calling endpoints that only bots would call), you won't get banned.

I actually have a script in Python that helps me "cleanse" my account, and I haven't been banned after using it for 2 years. 

Though that is great info, thank you for the response.
