### ISSUE TITLE
Serenity fails to even see modal submits...

### ISSUE THREAD

**Issue by cheesycod** [serenity-rs/serenity#2421]
```rust
use crate::{Context, Error};
use poise::{serenity_prelude::{CreateQuickModal, CreateInputText, InputTextStyle}, CommandOrAutocompleteInteraction};
use serenity::builder::{CreateInteractionResponse, CreateInteractionResponseMessage};

/// Unlocks RPC for a 10 minutes, is logged
#[poise::command(
    slash_command
)]
pub async fn modaltest(
    ctx: Context<'_>,
) -> Result<(), Error> {
    let qm = CreateQuickModal::new("Test")
    .field(CreateInputText::new(
        InputTextStyle::Short,
        "HI",
        "h",
    ));

    match ctx {
        poise::structs::Context::Application(a) =>  {
            match a.interaction {
                CommandOrAutocompleteInteraction::Command(c) => {
                    if let Some(resp) = c.quick_modal(&ctx.discord(), qm).await? {
                        let inputs = resp.inputs;
                        let h = &inputs[0];

                        c.create_response(
                            ctx,
                            CreateInteractionResponse::Message(
                                CreateInteractionResponseMessage::default().content(h),
                            ),
                        )
                        .await?;        
                    }                
                },
                _ => {
                    return Err("Not a command".into());
                }
            }
        },
        _ => {
            return Err("Not an application context".into());
        }
    }

    Ok(())
}
```

This code worked a few days ago but now serenity no longer even see's the response

Branch is serenity-next

**Comment by kangalio** [comment]
Serenity logs a warning that explains the issue:

```
[2023-05-08T18:01:48Z WARN  serenity::gateway::shard] [ShardInfo { id: 0, total: 1 }] Unhandled error: Json(Error("missing field `style`", line: 0, column: 0))
```

Caused by https://github.com/serenity-rs/serenity/pull/2393

This time it's not me misreading the docs, but the docs being wrong, though. The [Modal Submit Data Structure docs](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-modal-submit-data-structure) link to the [regular components docs](https://discord.com/developers/docs/interactions/message-components), which say that [InputText has a required `style` field](https://discord.com/developers/docs/interactions/message-components#text-inputs-text-input-structure). But there is no `style` field in the data sent by Discord.

![Screenshot_20230508_200922](https://user-images.githubusercontent.com/21220820/236900401-56352080-238a-4ec7-a1d3-11812f8635e5.png)


I asked on the Discord Developers server https://discord.com/channels/613425648685547541/697489244649816084/1105194562579865760 but as always it's hard to get qualified answers there. If nothing of value turns up there, we'll just have to make `style` optional and hope that Discord doesn't surprise us with more missing fields that are supposedly required.
