### ISSUE TITLE
Feature Flag "simd_json" causes failure to compile

### ISSUE THREAD

**Issue by Moocow9m** [serenity-rs/serenity#2474]
Serenity Version: Latest Release(11.5) and Latest Git Commit(9fc3f118)
Log: `https://pastebin.com/fzKUYSKh`

Temporary fix: Cloned to local path and updated simd_json to 0.9. Then set `serenity\src\json.rs:77` to `Ok(unsafe { simd_json::from_str(s)? })`. This works for my use case, but I would rather not maintain this. I plan to make it not use unsafe later.

**Comment by mkrasnitski** [comment]
This is unfortunately not possible to fix (in a satisfactory way) without introducing breaking changes. Note that this is in fact fixed on the `next` branch, so once 0.12 releases it should not be an issue. See #2353 for details, but in essence, `simd_json::from_str` can potentially break an invariant of its string argument by mutating it such that it no longer contains valid UTF-8. Therefore, passing in an `&mut str`, and then using the string later on, can lead to UB. This is the case even in versions of simd_json prior to 0.7, when the function was marked unsafe (prior to that it was basically just unsound).

Because `serenity::json::from_str` is public, patching this soundness hole requires changing the function to take ownership of its argument, to prevent the user from causing UB by using the string after it's been parsed. This is what #2353 did. I don't know what we should do on `current`. As it stands, simd_json support is entirely broken, but the soundness hole will still be exposed if we upgrade to a newer version without also changing the signature of `serenity::json::from_str`.

**Comment by Moocow9m** [comment]
I see. I'll just run a modified local copy for now then.

**Comment by kangalio** [comment]
Attempted fix in #2536

**Comment by kangalio** [comment]
Fixed in https://github.com/serenity-rs/serenity/pull/2610
