### ISSUE TITLE
Error: `Required item missing from cache` when fetching the member from a message

### ISSUE THREAD

**Issue by onlycs** [serenity-rs/serenity#2515]
I have a reaction after listening for a ReactionAdd event, and I want to get the member object from the message from the reaction event:

```rs
let message = reaction.message(&ctx).await?;
let member = message.member(&ctx).await?;
```

This fails with the error:
```
called `Result::unwrap()` on an `Err` value: The required item is missing from the cache.

Caused by:
    The required item is missing from the cache.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

And before you ask, yes, the bot has all privileged intents and has admin perms on the server

**Comment by arqunis** [comment]
This is intentional. `Message::member` uses the `Message::guild_id` field to first find the `Guild` instance, and then based on the `Message::author` field, tries to find the `Member` instance in the guild.

The `Message::guild_id` field is populated only if the message was received over the gateway. Fetching it via the HTTP API, like with `Reaction::message`, results in `None`.

It may be more useful to try to use data available in the [`Reaction::member`](https://serenity-rs.github.io/serenity/current/serenity/model/channel/struct.Reaction.html#structfield.member) field. If that's not what possible (because you need an actual `Member`, not just partial data), then searching the `Member` through its associated `Guild` may be more desirable. You can utilise the [`Reaction::guild_id`](https://serenity-rs.github.io/serenity/current/serenity/model/channel/struct.Reaction.html#structfield.guild_id) field to find the `Guild` and then via [`Reaction::user_id`](https://serenity-rs.github.io/serenity/current/serenity/model/channel/struct.Reaction.html#structfield.user_id) the `Member`. If `Reaction::guild_id` happens to be `None`, you can fall back to finding the `GuildChannel` with [`Reaction::channel_id`](https://serenity-rs.github.io/serenity/current/serenity/model/channel/struct.Reaction.html#structfield.channel_id), then the `Guild` it belongs, and finally the `Member`.

**Comment by kangalio** [comment]
Closing because question was answered and there are no follow-up questions
