### ISSUE TITLE
feature-request(next): ability to construct interaction events for easier unit testing

### ISSUE THREAD

**Issue by vidhanio** [serenity-rs/serenity#2527]
right now, all the structs are `#[non_exhaustive]`, meaning they are unconstructable. it would be useful if we could construct these with code, so that we can unit test our handlers.

**Comment by jonhoo** [comment]
I would very much also like this for the same reason. Unfortunately, there isn't a clear way to achieve this. People have asked for an "exception" for `#[non_exhaustive]` when used with `..Default::default()` syntax [before](https://internals.rust-lang.org/t/pre-rfc-relaxed-non-exhaustive-structs/11977), but unfortunately it [has problems](https://internals.rust-lang.org/t/pre-rfc-relaxed-non-exhaustive-structs/11977/15). One path forward might be to provide builders for the interaction events?

**Comment by jonhoo** [comment]
There is [this trick](https://internals.rust-lang.org/t/pre-pre-rfc-syntactic-sugar-for-default-default/13234/10?u=scottmcm) what we could maybe employ for types that are `Default` to at least have a semi-convenient way to override some of the fields.

**Comment by jonhoo** [comment]
Along the same lines, it'd also be helpful if `CreateInteractionResponse` and friends implemented `Deserialize` so that we could more easily mock a Discord server (and see that our client indeed sends sensible commands).

**Comment by GnomedDev** [comment]
Discord doesn't lend itself to mocking, especially in a compiled language like Rust. I would recommend using one of the many "mock discord's http/gateway" projects that get brought up when this is asked for, should be possible to find a working one with a search.

**Comment by Erk-** [comment]
We don't have `#[non_exhaustive]` on the structs in [Twilight](https://github.com/twilight-rs/twilight) because the models are in a seperate crate. Sadly that means that the twilight-model crate plays quite loose with semantic versioning because we are yet to find a good way of not breaking it whenever discord adds a new field or changes a field to be optional.

**Comment by jonhoo** [comment]
@GnomedDev I've gotten pretty far with mocking Discord for a bot I'm currently writing using [wiremock](https://docs.rs/wiremock/). The main thing I'm running into is that I have to deserialize the requests into generic `serde_json::Value` and then pick out the fields I care about, and then construct the JSON responses using `serde_json::json!({ ... })` rather than using well-typed values. Those aren't the end of the world, but the former would be made much nicer by also implementing `Deserialize` for the request types, and the latter less error-prone (I already spent an hour debugging a misspelled field) by having some way to construct Response types directly.

For former I think shouldn't be too painful (as in, I don't think the `derive(Deserialize)` are likely to cause too much trouble?). The latter is tricky as mentioned due to the (admittedly totally needed) `#[non_exhaustive]` annotations. But maybe it'd be possible to provide a constructor that takes all the required fields and returns `Default::default()` for the remaining ones (including any new ones added over time)?

**Comment by vidhanio** [comment]
> For former I think shouldn't be too painful (as in, I don't think the `derive(Deserialize)` are likely to cause too much trouble?).

I think the main reasoning why this isn't done is this: https://github.com/serenity-rs/serenity/issues/2324#issuecomment-1826012833

**Comment by jonhoo** [comment]
I think one can make the same argument for `Serialize`, no? _Technically_ someone might rely on the JSON that is produced, and so it'd be a breaking change if any of the fields internal to the builder changed. If anything, `Deserialize` is a little more forgiving since it (by default at least) is forward-compatible with added fields — if the data that is deserialized contains fields not in the struct, the deserialization will still succeed.

**Comment by GnomedDev** [comment]
Interaction already implements Deserialize, and is mockable by providing mock JSON data. We cannot allow direct construction as that is a semver hazard and disallows a lot of cool memory optimizations I've been working on. I do not see a way for this issue to move forward productively, so @vidhanio would you be okay with closing this?

The linked issue, #2324, is about implementing `Deserialize` on *builder* types, which is not going to be done for reasons there.

**Comment by jonhoo** [comment]
I think there are two "wants" here:

1. When constructing mock data to send to, say, an `Interaction` handler, to be able to ensure that the mock server has at least set all the required fields. It's totally possible to write `serde_json::json!` invocations manually and trying to ensure all the fields are set correctly, but it'd just be a lot nicer if it were possible to construct these directly in Rust code with auto-complete, compile-time checking, etc.
2. When receiving something like an interaction response back to the mock server, to be able to parse and validate that response. At the moment, the only type in `serenity` that represents an interaction response is the builder `CreateInteractionResponse`, hence the request for it to `impl Deserialize`, but I also see the argument for not wanting that on a builder.

Both of these are _possible_ today in the sense that it's always possible to send mock data with `serde_json::json!` and to parse responses into `serde_json::Value`. The request is whether there's a way to make either of these (probably quite common) testing workflows more ergonomic. The exact mechanism by which this happens isn't super important to me (nor, I suspect, to others running into this).

I'm totally fine with this being closed as a wontfix — after all, it's not really a blocker to using the library. It would just be nice to have some helpers for testing implementations that use the library is all :)

**Comment by GnomedDev** [comment]
Okay, what you are asking for is builder types for every discord model, which is not going to happen. 
As stated above, this is possible with mock json, but otherwise is not possible due to the static nature of Rust.
