### ISSUE TITLE
Intents are not used when using the raw `Http` client

### ISSUE THREAD

**Issue by Kerollmops** [serenity-rs/serenity#2663]
Hello 👋

Is there a way to provide the intent to the `Http` client? I tried creating a `Client`, providing the intents to it, and [querying messages](https://docs.rs/serenity/latest/serenity/http/struct.Http.html#method.get_messages), but the intents are not provided to the `Http` struct.

```rust
let client = ClientBuilder::new("token", GatewayIntents::MESSAGE_CONTENT).await?;
let channel_id = ChannelId::new(1234);
let messages = client.http.get_messages(channel_id, None, None).await?;
for message in messages {
    dbg!(message);
}
```

Thank you for your help.

**Comment by arqunis** [comment]
> Is there a way to provide the intent to the `Http` client?

There is none, because intents are for the gateway only. Discord's HTTP API does not allow you to provide intents, even for ones that aren't associated with any gateway event in particular, like `MESSAGE_CONTENT`.

**Comment by Kerollmops** [comment]
So, is there a way to get all message content in a specific channel? Should the HTTP API always return the content? Because I am constantly seeing an empty string as the content?

**Comment by arqunis** [comment]
I am honestly not sure. I haven't had the need to fetch a `Message` object with the content via the HTTP API, and the documentation for the [Get Channel Messages](https://discord.com/developers/docs/resources/channel#get-channel-messages) endpoint does not mention the intent at all (nor other related endpoints). I can only speculate two things:

1. You may only receive the content of a message via the gateway. Similar for being able to receive the full `Guild` object rather than the `PartialGuild` object you get from the HTTP API.
2. When you work with the gateway, to enable or disable intents you must specify them in the "Identify" payload upon first connecting to the gateway. Certain intents, however, require you to enable them first in your bot's developer settings, because they are privileged. `MESSAGE_CONTENT` is one of these. Since the HTTP API does not let you enable or disable intents much like the gateway does, it could be assumed that *all* intents are enabled by default. It's just that for privileged intents, they also have to be enabled in the bot settings.

If it is 2., could you verify if you have this toggle switch turned on?
![image](https://github.com/serenity-rs/serenity/assets/16745149/199d8002-212a-4878-8487-b99e428e775e)

**Comment by Kerollmops** [comment]
> If it is 2., could you verify if you have this toggle switch turned on?

You are my savior! It was indeed the issue, thank you very much 👍
