### ISSUE TITLE
CreateButton::new documentation disagrees with Discord documentation

### ISSUE THREAD

**Issue by jonhoo** [serenity-rs/serenity#2706]
The [`CreateButton::new` documentation](https://docs.rs/serenity/0.12.0/serenity/builder/struct.CreateButton.html#method.new) states

> Clicking this button will not trigger an interaction event in your bot.

However, the [Discord documentation](https://discord.com/developers/docs/interactions/message-components#buttons) claims:

> They can be clicked by users, and send an [interaction](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object) to your app when clicked.

and

> When a user clicks on a button, your app will receive an [interaction](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object) including the message the button was on:

I do see the disclaimer that

> Link buttons do not send an [interaction](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object) to your app when clicked.

But that appears to only affect link buttons (i.e., `CreateButton::new_link`), not non-link buttons.

If the `serenity` documentation is indeed wrong here, may be worth updating as I walked in circles here for a bit trying to find a different way to handle a problem rather than using buttons as a result of that line in the documentation :sweat_smile:

**Comment by CenTdemeern1** [comment]
From my experience, it's in a bit of a weird spot where your event handler won't receive an event directly, but you have to explicitly `get_response` (or equivalent) to get the message your button is attached to, and then you have to explicitly `await_component_interaction`.

This does not seem to be explained *anywhere* and I suffered for a solid 4+ hours today trying to figure this out. I do think this should be implemented or documented better.

A lot of things attached to interactions don't seem to be documented very well. I spent those same 4+ hours trying to figure out how to display a modal with a dropdown.<br>Turns out you can't and this isn't clearly documented.<br>The only thing the documentation says is that "InputText is only valid in modals!":
![Screenshot 2024-01-11 at 22 39 33](https://github.com/serenity-rs/serenity/assets/24682280/568dd0b6-16f3-4d8b-9cb1-b18b29fc6ce8)
What they actually meant to write is "InputText is the only valid option in modals!" (or maybe in addition to what is currently written)<br>I chased down rabbit holes, one after another, looking for the type "4" that was apparently the only valid value the vague error referred to, only to find hours later that that is referring to InputText. Again, barely documented.

**Comment by mkrasnitski** [comment]
Seems like #2633 addressed this.
