### ISSUE TITLE
Can't seem to pass in a Receiver or Sender

### ISSUE THREAD

**Issue by mwotton** [serenity-rs/serenity#330]
I have code in this gist:

https://gist.github.com/mwotton/96dbdec4efb3554854370c63e4108c9c

I understand that Receivers can't be cloned, and Senders need to be cloned if you want multiple threads to talk to the same (rust) channel. However, I can't seem to convince rust that the Receiver I'm passing in has no other users. Is there an example of passing channel components into Serenity clients somewhere? It seems like a reasonable use case, but I'm having real trouble with it.

**Comment by acdenisSK** [comment]
This issue is more Rust related than it is serenity, but I'll still give you an explanation why this isn't allowed:

The error complains how `Sender` and `Receiver` do not implement `Sync`. Wait, what's `Sync` exactly?
[A trait that ensures that a given type can be safely referenced (`&T`) between threads.](https://doc.rust-lang.org/nightly/std/marker/trait.Sync.html) Which both [`Sender`](https://github.com/rust-lang/rust/blob/master/src/libstd/sync/mpsc/mod.rs#L501) and [`Receiver`](https://github.com/rust-lang/rust/blob/master/src/libstd/sync/mpsc/mod.rs#L341) can't be, no matter what type they're sending or receiving.

Now, why we have to deal with `Sync` at all in the first place is due to serenity's dispatch code; it's threadpool'd and quite complex, so we share the `EventHandler` you gave a lot in many places (hence why it has a [`Sync`](https://github.com/serenity-rs/serenity/blob/master/src/client/mod.rs#L332) bound).

So what we need here is a construct (abstraction) that'll make our type `Sync` as well. The Standard Library thankfully provides us with such, the [`Mutex`](https://doc.rust-lang.org/nightly/std/sync/struct.Mutex.html)
```rust
use std::sync::Mutex;

struct Handler {
    sendToBackend: Mutex<Sender<FWMessage>>,
    recvFromBackend: Mutex<Receiver<FWResponse>>
}
```
and then when using them:
```rust
let sendToBackend= sendToBackend.lock().unwrap();

sendToBackend.send(FWMessage { .... }).unwrap();

...

let recvFromBackend = recvFromBackend.lock().unwrap();

let response = recvFromBackend.recv().unwrap();
```
Adjusting your code it *should* make the error go away and give you a reprieve.

Oh and also, at this [`line`](https://gist.github.com/mwotton/96dbdec4efb3554854370c63e4108c9c#file-channel-rs-L158), please do not gobble your function like this. 
- the `<'a>` is unnecessary because we're not enforcing that some reference should live as long as `'a`; 
- `&String` is useless:
    - when accepting strings this kind would *only* make sense if we were needing to read its capacity for
some reason, but we do not, so `&str` is better to be used here;
- `-> ()`: All functions who do not specify their return default to the unit type (`()`), also unnecessary.

**Comment by mwotton** [comment]
ah, cheers. Yeah, the <'a> thing was a result of random fiddling I forgot to take out. The str/String thing is good to know.

Still mildly annoying that we've got to invoke a mutex for something that will not ever be used elsewhere, but I suppose this isn't performance-oriented code. Thanks for the detailed response!
