### ISSUE TITLE
Voice Opcode 6 not recognized.

### ISSUE THREAD

**Issue by expert700** [serenity-rs/serenity#390]
I am encountering the following error on version 0.5.9:
```
WARN serenity::voice::connection > Error deserializing voice event: Error("unknown VoiceOpCode value: 6", line: 0, column: 0)
```
Looking at past issues, it seems like there was a fix at some point (https://github.com/serenity-rs/serenity/commit/7d162b96686a56eed052984c18f22f54ad76f780), but the opcode is now gone from the voice opcode enum again, and that commit doesn't show up in the commit log, so I don't really know what happened there...

**Comment by zeyla** [comment]
The commit mentioned was merged into the WIP v0.6.x branch. We can't add support for this in 0.5.x as this would require adding another event variant, which we can't do in the current version as it breaks backwards compatibility in Rust. 0.6.x contains support for this, and will also make enums and structs non-exhaustive to prevent API breakage.

I've removed logging this in this commit: 08511da. In your logger I'd suggest filtering this out until 0.5.10 lands, since the event not being deserialized is non-important.

Thanks for the issue
