### ISSUE TITLE
Example 11 doesn't contain color

### ISSUE THREAD

**Issue by PenetratingShot** [serenity-rs/serenity#464]
I noticed that in example 11 (where it shows how to use the message builder), it made no specification of embed color. I'm assuming that it's `.color(value)` however I'm not quite sure.

**Comment by Mishio595** [comment]
`CreateEmbed::colour` and `CreateEmbed::color` (do the same thing) take a parameter that implements `Into<Colour>`, see [the CreateEmbed docs](https://docs.rs/serenity/0.5.11/serenity/builder/struct.CreateEmbed.html#method.colour).

Looking at the [Colour docs](https://docs.rs/serenity/0.5.11/serenity/utils/struct.Colour.html) you can see that `From<i32>`, `From<u32>`, `From<u64>`, and `From<(u8, u8, u8)>` are implemented, meaning these are all accepted values. You can also implement `Into<Colour>` on your own structs in order to adopt this behaviour.
