### ISSUE TITLE
arg single doesn't break across lines (0.5.12)

### ISSUE THREAD

**Issue by JellyWX** [serenity-rs/serenity#504]
Take the following:

```rs
args.single::<String>();
```

The argument doesn't break if the input breaks across lines, only if there is a space character at the end of the previous line, so something like 

```
.command arg1
bunch of text related to command
```

the single arg is `arg1\nbunch`

Potentially this is intentional but it feels strange

**Comment by acdenisSK** [comment]
This is by design. `Args` works by way of *delimiters* that serve as indicators for distinct arguments.
If a user doesn't provide their own bunch of delimiters, we set the space character as the default.

For `single` to work as you expect, you need to configure the framework to split by newlines as well.
This can be achieved with [`Configuration::delimiter`].

[`Configuration::delimiter`]: https://docs.rs/serenity/0.5.12/serenity/framework/standard/struct.Configuration.html#method.delimiter
