### ISSUE TITLE
Rewrite the lib in Go

### ISSUE THREAD

**Issue by arqunis** [serenity-rs/serenity#524]
Generics are overrated and redundant. OS threads are slow, green threads are the kings. GC is the layman's choice of memory management; why bother dealing with freeing resources myself?

We should strive for simplicity, not complexity. We must convert to the Gopher's way.

**Comment by Texlo-Dev** [comment]
I second this attempt. Go handles concurrency and memory management in a very efficient manner which ensures the best possible experience for the end user.

**Comment by Lakelezz** [comment]
I have decided that we shall hold a referendum!
Please vote whether to gopher to not to gopher. 

If we gopher, then Serenity will leave the Ferris Union at the end of year 4593 on 1st of April.

**Comment by Mishio595** [comment]
![](https://blog.golang.org/gophergala/fancygopher.jpg)

**Comment by Erk-** [comment]
You will need to specify what language you mean because I think Go! is better for this than Go by google

**Comment by allquixotic** [comment]
Go is an unacceptably slow language for anyone doing any form of [serious computation](https://benchmarksgame-team.pages.debian.net/benchmarksgame/faster/rust-go.html). 

You wouldn't be able to tell the difference for a bot that just posts memes in a single channel on a single Discord server; you could write that in Microsoft VB6 and it'd still be fine. But I am working on writing bots that may do serious computation; if not in reaction to an individual command, then certainly it would start to feel like serious computation in terms of CPU usage, when many hundreds of users are hitting the bot at scale. I have no desire to "shard" my bot and make many instances of it; and even if I were forced to do that, writing my program in Rust would minimize the required CPU and memory usage per user and therefore maximize scalability and minimize cost of the servers involved.

I chose serenity-rs as my Discord API wrapper for this reason. It would be a real shame to see it stop being maintained because the maintainers wanted to focus all their efforts on a Go reimplementation. I have no qualms about folks writing a Go Discord bot client; by all means, go and do it! I don't want to stop anyone from doing something fun/interesting, especially when it's open source.

But serenity-rs has a very important role, IMO, as an in-process, language-native Discord bot library for anyone desiring to write a bot built for efficient scalability (running lots of computation or lots of concurrent users on a single server, in a single process). In my opinion, anyone releasing a "public" bot that potentially hundreds or thousands of users would want to use, across many Discord servers/rooms, should write their bot in C, C++, or Rust to minimize the hosting cost of their bot. If you start using GC and a language that's 5-10x slower than C/C++/Rust, you're looking at potentially much higher hosting costs.

I would ask that any committers for serenity-rs who like the Go rewrite continue to at least contribute bug fixes part-time to serenity-rs to keep this library usable. It's very good in the state it's in now, but as Discord evolves, the library may need to evolve to keep up. 

Of course I can't dictate how people spend their spare time, but please give proper consideration and respect to serenity-rs and the Rust ecosystem as an excellent solution to the problem of "I want the performance of C/C++ without the danger". Discord bots are being written to do all sorts of crazy things that are memory and CPU-hungry, especially when you release a public bot that tons of people want to add to their servers. It's going to be a lot harder (and costlier) to maintain and scale those big, popular bots if they're being written in slower languages. Just ask some of the more popular bot maintainers who already operate bots written in some slower language, and you'll see what they have to go through.

**Comment by Mishio595** [comment]
Please take a moment to look at the date this issue was opened.

**Comment by arqunis** [comment]
@allquixotic pardon, but it seems I'll have to amplify the reasoning of this issue's existence: 
It's a joke. For April Fools.

The date may be claiming that it was opened on the 31th of March, however I didn't want bother myself staying 4 hours past my bedtime considering I also had school to wake up for. That's why I opened this earlier than the fools holiday.

Absolve me of any rudeness you might perceive, but if you were a little more aware of the context, you wouldn't have wasted writing hefty 5 paragraphs over this.

**Comment by allquixotic** [comment]
Oh god, haha! I got April Fooled in May! Silly me. No rudeness perceived; thanks.

In that case, I nominate this issue for swift closure. Maybe next year you can do an April Fools about rewriting serenity-rs in Swift ;)
