### ISSUE TITLE
Command is not dispatched when the group is defined with a prefix.

### ISSUE THREAD

**Issue by nickelc** [serenity-rs/serenity#565]
Even if the group prefix is same as the global prefix the command is not dispatched.
```rust
group!({
    name: "owner",
    options: {
        prefix: "+",
    },
    commands: [ping],
});

#[command]
fn ping(ctx: &mut Context, msg: &Message) -> CommandResult {
    if let Err(e) = msg.channel_id.say(ctx, "pong") {
        eprintln!("command error: {:?}", e);
    }
    Ok(())
}

client.with_framework(
    StandardFramework::new()
        .configure(|c| c.prefix("~"))
        .group(&OWNER_GROUP)
);
```

**Comment by arqunis** [comment]
Should be fixed in [c:b1eff27](https://github.com/serenity-rs/serenity/commit/b1eff278bdb876612f5ab99a566e680ffc1db11a).

**Comment by nickelc** [comment]
While the issue is fixed for the case when both global and group prefixes are the same, the command is still not dispatched when owner prefix is different.

**Comment by arqunis** [comment]
Are you sure? It works as expected for me.
```rust
group!({
    name: "owner",
    options: {
        prefix: "+",
    },
    commands: [ping],
});
```

![image](https://dl.dropboxusercontent.com/s/6m4rohr44ilth21/DiscordCanary_2019-05-21_21-34-32.png)
(`???` being the global prefix)

I've also tested cases for groups without/with prefixes; subgroups with prefixes (they must have at least one); commands/subcommands and all of them executed correctly as desired.

**Comment by nickelc** [comment]
Oh, group prefixes are added to the global prefix. i totally missed that point.

**Comment by nickelc** [comment]
tested with `v0.6.x` branch
```rust
group!({
    name: "owner",
    options: {
        prefix: "+",
    },
    commands: [ping],
});

group!({
    name: "general",
    options: {},
    commands: [ping],
});
```
`~ping` and `~+ ping` works but `~+ping` does not work.

**Comment by nickelc** [comment]
so, knowing that the global prefix is required for the group commands with prefix I tested again against `0.6.x-rc.1` from crates.io and everything works as expected in the example from my previous comment.
`~ping`, `~+ ping` and `~+ping` works.

I'm so sorry for all the trouble.

**Comment by arqunis** [comment]
`~+ping` works because the rc on crates.io parses group prefixes and commands independent of whitespace.
That is, it takes a subslice of the message from its current position up to the length of the group prefix and tests whether slice equals to the prefix.
I.e `&msg[pos..pos+"+".len()] == "+"`

[This turned out to be a bad idea, as it introduced some unreasonable behaviour with commands (or group prefixes) that shared the same beginning](https://github.com/serenity-rs/serenity/issues/554) and had to disable it.

If you want to re-enable it though, set `Configuration::by_space` to `false`:
```rust
client.with_framework(|f| {
    f.configure(|conf| conf.by_space(false))
    // ~~~~
});
```

With that being said, I believe we can close this issue for good.
