### ISSUE TITLE
Voice Redesign

### ISSUE THREAD

**Issue by Erk-** [serenity-rs/serenity#633]
This was previously a discussion in the voice team but it would be better to have it here in public
(ping @FelixMcFelix @Flat)

**Comment by FelixMcFelix** [comment]
Copied from the internal discussion...

---

A concern I have with voice is that many external operations (play, pause, volume set/check) rely upon locking a shared object. This introduces an extra layer of busy-work for users while making it possible for them to carelessly block the audio thread. This is something we need to be careful about when we introduce callbacks.

Some ideas I have for this:

* Keep a similar design to what we have now. Users have direct access to LockedAudio objects and callbacks would presumably offer direct access to these same objects. We make the risks of performing any operations explicit in our documentation.

* Move to a command-based aproach. Users are given an AudioFacade (or similar object) to send individual commands/requests to the audio thread, which it then executes between requests for audio frames. More complex logic can be sent as a closure, a sole point in the API where we need to make the risks of blocking apparent. This also presents a good opportunity to isolate other sources of blocking (packet sends, mallocs, etc).

In the first case, thread blocking (and potential audio glitches) are still liable to happen. I'm not convinced that an RwLock would help, because the audio thread always requires write access to the audio source.

The second case, while minimising user-caused blocking, makes it harder for users to query an Audio object (as they must now wait for a reply from one of the audio threads). We can cache things like metadata, which should be static, but this could be a pain point.

**Comment by Flat** [comment]
Original discussion start. Any additional feedback welcome.

> **Topics and ideas to rework the voice modules to be more user friendly and feature complete.**
> Suggestions:
> 
> 
> - Replace youtube-dl and ffmpeg command calling with rust native libraries or FFI
> -  Provide metadata from playing tracks that are accessible from commands such as title, artist, filename, bit-rate etc. (via ffprobe, website api or scraping)
> - Callbacks for audio status (Finished, error, started, etc)
> - Optional parameters to disconnect or stop sub-processes automatically if no other users are in the channel, or if the bot in not in a voice channel
> - Add examples for queuing tracks

**Comment by MOZGIII** [comment]
Just so that I understand the current design on serenity overall correctly - when command handler reaches interacts with the system it may performs various blocking operations (i.e. lock, io, etc) and all of them do actually block the thread?

**Comment by MOZGIII** [comment]
I'd suggest providing users with control handles (play/pause/stop) for controlling the audio playback per "player". The reason is player itself should be owned by some system-internal unit (i.e. coupled with voice channel management), and the access pattern we should use there is calls into a remote control loop.

Regarding youtube-dl, I'd very much prefer to embed the youtube-dl and python interpreter. This would allow lower-level access to youtube-dl logic (which is the best we can have currently, as I understand, cause even lavaplayer's not as feature-rich).

New voice design should be async-compatible. Maybe we can go ahead with implementing it async right now, and then simply invoking it's control structures from `futures::executor::block_on` - this works fine for my other code bases.

In addition, we can implement some independent logic, cause `serenity` is not the only discord API crate available out there.

**Comment by Flat** [comment]
I think an entirely separate crate with external API would be the way to go and would also allow other libraries to use the functionality similar to lavaplayer while keeping the serenity codebase clean and without unnecessary dependencies. Regarding async though I still believe waiting until it is stabilized to implement would be better, or write the code now targeting beta and do not release until stable so it can be created and tested but not officially supported.

Re: other discord crates, are there? I hadn't seen others aside from discord-rs which hasn't been active for quite some time.

**Comment by FelixMcFelix** [comment]
I've looked into async'ing it before: we need to be extraordinarily careful about separating the hard real time parts of the system (producing and sending audio frames) from handling control signals and events from discord.

I agree on the separate crate.

-- Kyle

**Comment by MOZGIII** [comment]
Regarding the hard realtime - do we really? Isn't it safe to just send the whole audio stream over the socket at once, compared to sending it over frame-by-frame with 20ms delays?

**Comment by MOZGIII** [comment]
I mean, there's no hard realtime when we speak about the conventional networking hardware, there's only soft realtime really. And even with that in mind - can't discord server just prebuffer the whole audio stream and them play it back to the clients as the time goes?

**Comment by MOZGIII** [comment]
> Re: other discord crates, are there? I hadn't seen others aside from discord-rs which hasn't been active for quite some time.

https://github.com/dawn-rs/dawn
I could also use an audio player to implement audio playback support at my https://github.com/MOZGIII/netsound

We're safe to start with implementing async support targeting `beta` rust for now, if we want to use new `async/await` keywords. Luckily, we can go even without `async/await` keywords - just implement all the futures manually. I'm pretty sure though, that by the time we'll be ready to ship it `async/await` will be available on `stable`.

The problem with the current design is it uses threads where we could easily use tasks.

**Comment by MOZGIII** [comment]
Regarding `youtube-dl`, I did some experiments, and it seems we're better off using the `youtube-dl-api-server` (https://github.com/jaimeMF/youtube-dl-api-server) for audio info extraction, and then take care of actual downloading at the rust code.

**Comment by FelixMcFelix** [comment]
`can't discord server just prebuffer the whole audio stream and them play it back to the clients as the time goes?`
Even if it works, I don't think discord would look too fondly on this---I'll test it out to see whether it just dies or the clients buffer locally/go into an accelerated catchup. If it does work, it strips all the interactivity from stream control (there's no way to prevent clients from using packets which have been sent).

`we're better off using the youtube-dl-api-server ... and then take care of actual downloading at the rust code.`
Agreed. We should look into using this alongside the actual ffmpeg FFI bindings.

**Comment by MOZGIII** [comment]
Well, we might not be able to send the whole stream at once - i.e. a 100 MB file, cause that'd require the buffer size at discord end to be enormous. However, I'm pretty sure that we can send packets without strict 20ms intervals. A buffer holding up to 120 ms would be reasonable to expect from discord servers, based on that's the opus' max packet size. Yet, the buffer *might* be even bigger than that, and might even be dynamically growing. However, the 120 ms already relaxes the soft-real time requirement significantly. Ultimately we should first try just sending more data as it gets ready, and then think of timings if needed.

**Comment by MOZGIII** [comment]
For the playback logic, I think `mvp` could be a good inspiration in terms of the feature set, exposed configuration and the design overall. Even if not, here's their options manual: https://mpv.io/manual/master/#options It demonstrates what people do for the full-featured av player, so a sort of reference to what we can do.

**Comment by MOZGIII** [comment]
As for the implementation, you might find this interesting: https://github.com/MOZGIII/netsound/tree/master/src/io
This is an implementation of the `AsyncRead`/`AsyncWrite`-like traits, but generalized based on the data type instead of it just being `u8`. I use it for working with PCM samples: `f32`, `i16`, `u16`. We can adopt a similar design for the playback crate interface.
