### ISSUE TITLE
GuildChannel::edit() deadlocks when called with a GuildChannel from the cache

### ISSUE THREAD

**Issue by dthul** [serenity-rs/serenity#676]
As discussed on Discord yesterday, it is easy to trigger a deadlock when retrieving a channel from the cache and then trying to call `edit` on it:

```rust
use serenity::model::channel::Channel;

// Step 1: Retrieve a channel from the cache
let channel = channel_id.to_channel(&ctx)?;
if let Channel::Guild(guild_channel) = channel {
    // guild_channel is of type Arc<RwLock<GuildChannel>>
    // Step 2: Acquire the channel's lock and call edit()
    guild_channel.write().edit(&ctx, |channel_edit| channel_edit.topic("Some topic"));
}
```
This deadlocks because `edit` [calls `user_has_perms` internally](https://github.com/serenity-rs/serenity/blob/45d44cbd65938a8d1f8f65ff865b45316f11a48e/src/model/channel/guild_channel.rs#L368), which in turn retrieves the channel from the cache (again) and [tries to acquire a read lock](https://github.com/serenity-rs/serenity/blob/b49719f327403b91a351bdacb266084c0cd8d005/src/model/utils.rs#L294).
One solution might be to make `user_has_perms` take a channel object instead of just a ChannelId, such that it does not need to retrieve it from the cache.

**Comment by arqunis** [comment]
The [read lock can easily be eliminated](https://github.com/serenity-rs/serenity/pull/678) by supplying the utility function the guild id that we are already in possession in 86% (12/14) of the cases (including the `edit` method), since that's the data it has to get from the channel. However, it appears that this issue has even deeper roots. At the end of its body, the function calls the [`Guild::permissions_in`](https://github.com/serenity-rs/serenity/blob/b49719f327403b91a351bdacb266084c0cd8d005/src/model/utils.rs#L318) method which also tries to [acquire a read lock](https://github.com/serenity-rs/serenity/blob/current/src/model/guild/mod.rs#L1352) to the channel, resulting in a deadlock yet again. 😐

**Comment by arqunis** [comment]
Uh, should've dropped that statement entirely, I suppose? Anyway, ignore that.

**Comment by Lakelezz** [comment]
This should not happen anymore with how the cache works now in v0.9.
