### ISSUE TITLE
Add Color type alias for Colour

### ISSUE THREAD

**Issue by wackbyte** [serenity-rs/serenity#702]
I noticed while making a bot that there's only a `Colour` type. There's already an alias method for embeds. Can someone please add this?

**Comment by Lakelezz** [comment]
Hello, thanks for your issue :)

It's correct that the current API offers American and British English variants where possible and this makes your request valid.

However, it also raises the question whether we want to keep supporting both.
Internally we decided that Serenity will use British English, we came to this decision via poll quite a bit ago.

Anyway, that part has been decided already and won't be changed. Nonetheless, it's up to decide whether we still want to provide this overhead of localisation for the next breaking real release.
If we come to the conclusion to support it, then it is an easy decision to provide an alias here too.
Otherwise... it's up for debate whether we should still include this alias to keep 0.6 consistent.
