### ISSUE TITLE
Async and Futures

### ISSUE THREAD

**Issue by MOZGIII** [serenity-rs/serenity#729]
It's time to revisit #298.

**Comment by MTRNord** [comment]
This is still sadly blocking a project of mine :( cant use it with other messaging services that use another "tokio thread system"

**Comment by TapGhoul** [comment]
I am talking with the peeps on Discord, I may look into trying to do this. It's not a small task but it's definitely something I'm open to investigate. Will be looking at the tokio 0.2.0 branch (std futures).

**Comment by TapGhoul** [comment]
Update: Until async fn is available for traits, you can't really expose this to the user in an ergenomic fashion (making all the callbacks async) without using something like async-trait - which in of itself feels like a bit of a hack. We can expose the tokio runtime instance - and even allow you to provide your own - however there is no perfect solution as of yet, sadly.

I can look into updating everything under the hood, but the end result will not be as nice as I would have hoped, due to missing key rust features for this to work properly. I don't know if I'll commit to this as of yet as the payoff I'm hoping for is blocked by async fn in traits.

See: https://areweasyncyet.rs/

**Comment by mgostIH** [comment]
@Silvea12 Since async in traits is still quite a hard blocker, what about using [async-trait](https://crates.io/crates/async-trait) until they get stabilized? I don't think the performance impact of allocating would be a huge deal in this project and it would allow to easily continue the development instead of stalling for what may be 1+ years.
Moreover, switching from the crate to the stable feature would be painless, as you just need to remove a macro.

**Comment by TapGhoul** [comment]
@mgostIH I had looked into that. My 2 worries are lock-in, as well as the fact that the end user is, as a result, required to also use the macro if they are to extend the client, which makes it more difficult for new rust users to reason about at a glance (I struggled with this a bit when I was initially learning) - but it's definitely been a consideration.
My thoughts as an ideal (in my head) solution was mentioned in my above comment.

> We can expose the tokio runtime instance - and even allow you to provide your own - however there is no perfect solution as of yet, sadly.

We can run each call on its own async call (though coming from go this is bad practice - but this is what other libraries acting as runtimes had done anyway which I found quite ergonomic to use) as a standard call and just provide an instance to the tokio runtime to allow for users to spin off tasks from these async-wrapped sync calls. It's slightly higher overhead, but it means less (even if still minimal) boilerplate.
Means that if you don't care about async, your stuff is already run on a thread pool. If you do, however, you can quite easily take full advantage of the tokio runtime.

I've meant to work on this but sadly my weekends have been taken up with other work. I hope to make some progress on this soon, and may go with async-trait in the end if I feel that usage-wise it's worth the extra mandatory import as the end user.

_Edit: clarification, grammar and added reasoning._

**Comment by Lakelezz** [comment]
Just to note it here: Async Serenity is currently being developed.

**Comment by MTRNord** [comment]
@Lakelezz just wondering: Is there anything yet we can try out? If not that's totally fine too :) Just wanted to check if there is anything to test yet.

**Comment by Lakelezz** [comment]
I successfully ported example 5, including commands, help, checks, and everything else.

The API hereby will remain the same mostly, none of the check, help, or command signatures will be altered. The construction of the framework became part of the client construction. This has an internal reasoning to further optimise the dispatch performance. 

Here are some things that need to be done:
- Porting Voice, did not touch at all;
- Updating all docs including doc tests;
- Updating benchmarking;
- Porting all the other examples;
- Merging current changes, which is a bit difficult, as all that is blocking code requiring a bit of rewrite;

Future plans are to add a collector-like system, for such discussions see: #786
That should be everything :)
I can consider releasing the code soon, if you are interested.

**Comment by Lakelezz** [comment]
Just to point it out here too, asynchronous Serenity is ready to be tested, head here to follow the process: https://github.com/serenity-rs/serenity/pull/803

**Comment by MTRNord** [comment]
Just wanted to report that it seems to run very stable :) Thanks for all the work!

**Comment by Lakelezz** [comment]
> 
> 
> Just wanted to report that it seems to run very stable :) Thanks for all the work!

Glad to hear that! Make sure to update often, I applied some bugfixes related to hook functions!

**Comment by Lakelezz** [comment]
This is done and has been released v0.9 :)
