### ISSUE TITLE
Decoding opus frames fails with opus produced by ffmpeg

### ISSUE THREAD

**Issue by jtscuba** [serenity-rs/serenity#833]
Serenity Version: `0.8.3`
Rust: `rustc 1.42.0 (b8cedc004 2020-03-09)`

ffmpeg version `4.2.2`

`ffmpeg -i assets/lion-roar.mp3 -ar 48000 -ac 2 -acodec libopus -b:a 128000 -vbr on -compression_level 10  -application audio -f ogg assets/lion-roar.ogg` produces a playable file. 

However, `ffmpeg -i assets/lion-roar.mp3 -ar 48000 -ac 2 -acodec libopus -b:a 128000 -vbr on -compression_level 10 -map 0:a  -application audio -f data assets/lion-roar.ropus` and then trying to read frames with serenity

Ran with RUST_LOG=trace but no errors or exceptions occured
```
let file = File::open("assets/lion-roar.ropus").unwrap();
    let mut source = opus(true, file);
    let mut local_buf = [0f32; 960 * 2];
    println!("{:?}", source.decode_and_add_opus_frame(&mut local_buf, 1.0));
    //outputs: None
```

The ropus frames seem to have the correct format `Stream #0:0: Audio: opus (libopus), 48000 Hz, stereo, flt, 128 kb/s`

@Flat asked me to open this issue in discord

**Comment by FelixMcFelix** [comment]
I'm currently working on redoing audio, and these functions had me scratching my head for a bit until I looked at history for `read_opus_frame` et al. The `opus` function and related AudioType do not do what they should. It was misnamed by the implementor – it reads Opus frames from DCA1 container files, whereas a real opus file exists in the Ogg container format. This is not the expected behaviour.

[DCA1](https://github.com/bwmarrin/dca/wiki/DCA1-specification) is, to the best of my knowledge, only used by a few discord libraries, so ffmpeg is unlikely to support it as an output format.

In the mean time, please use `voice::ffmpeg`, which can naturally read Ogg containers. I hope in future to separate out codecs and containers.

**Comment by Lakelezz** [comment]
As audio has been reworked, I will close this. If the issue persists, please inform us :)!
