### ISSUE TITLE
Add `fmt` to Serenity

### ISSUE THREAD

**Issue by Lakelezz** [serenity-rs/serenity#847]
Add the Rust code formatter to Serenity.

**Comment by dmarcoux** [comment]
I could set this up in the CI and beforehand format the files with `rustfmt`. However, the [CONTRIBUTING.md](https://github.com/serenity-rs/serenity/blob/2a54410f79d0918925fa0ca02607e5b073f0e247/CONTRIBUTING.md#code-style) is clearly stating the opposite in the `Code Style` section:

>We don't follow rustfmt because it often produces unreadable results.

So is using `rustfmt` really something the maintainers want?

**Comment by arqunis** [comment]
The opinion about `rustfmt` contained in the contributing guide may still be true (it kept giving us ugly results), especially when running it without configuration and letting it decide the style itself. However, that used to be around 3-4 years ago, when configuration options were sparse or nonexistent (i.e., options that could permit us to avoid the ugly results). It's been an eternity since, and `rustfmt` has definitely improved during that period. Therefore, we have decided to lift the restriction stated in `CONTRIBUTING.md` and format every Rust file from now on. 

Well, I say "from now on", but not really. We're going to begin formatting Rust files with `rustfmt` after all PRs are merged or closed, including the async/await PR. Addressing this issue right now would conclude in a nightmare of merge conflicts, neither which I or authors of the PRs would like to experience and fix.

You don't have to concern yourself with this issue for the time being.

**Comment by Lakelezz** [comment]
`fmt` is part of Serenity.
