### ISSUE TITLE
voice_state_update issue

### ISSUE THREAD

**Issue by NickTsaizer** [serenity-rs/serenity#902]
Good day! 
I found an issue with "voice_state_update". It needs 4 arguments (and it works ok with them), but I can see those warnings:

![image](https://user-images.githubusercontent.com/17569464/86539302-06053380-bf04-11ea-9ea8-a77585fa076b.png)

Also i cant find where i can get voice chat user counter.
![image](https://user-images.githubusercontent.com/17569464/86539160-27195480-bf03-11ea-8ab1-155aad2e4797.png)
plz help me.

And sorry my english, im just stupid.

**Comment by arqunis** [comment]
This is not an issue, it's intentional. Based on whether you have the `cache` feature enabled, [the `voice_state_update` handler may either have three or four parameters](https://github.com/serenity-rs/serenity/blob/current/src/client/event_handler.rs#L296-L308). Discord does not provide the previous state of data, so we must cache most things if we want to pass on this old version of the data to the consumers of the library. If the cache is disabled, we can't do that.

If your code compiles and works with the four parameters, then don't mind this warning. It's likely your IDE is unable to recognize the feature flag and apply it. 

> Also i cant find where i can get voice chat user counter.

Would you mind clarifying? Do you mean how many users are in a voice channel?

**Comment by NickTsaizer** [comment]
Yep. I just need to check how many users connected to voice channel when one of them left. I can get channel object, but it has not .users or .user_count() or something like that.

**Comment by arqunis** [comment]
There isn't a dedicated function for this task, but you can implement one yourself. [The library keeps track of all voice states in a guild](https://docs.rs/serenity/0.8.6/serenity/model/guild/struct.Guild.html#structfield.voice_states). You can filter these based on the channel of your interest to get the amount of users in the channel.

```rust
fn user_count(guild: &Guild, channel_id: ChannelId) -> usize {
    guild
        .voice_states
        .values()
        .filter(|state| { 
            match state.channel_id {
                Some(c) => c == channel_id,
                None => false,
            }
        })
        .count()
}
```

**Comment by NickTsaizer** [comment]
Ok, thanks!
