### ISSUE TITLE
Obscure and non-descriptive error message for a common failure case

### ISSUE THREAD

**Issue by kangalio** [serenity-rs/serenity#919]
When trying to send an invalid message via serenity, for example a message with an empty message body, serenity rightfully returns an error. However, this error is very non-descriptive and super hard to handle correctly due to its nested nature.

The error message says `[Serenity] No correct json was received!` which is not indicative of its cause at all.

Furthermore, this error type is incredibly nested - this is the code that's needed to check whether the message we sent was valid or not:
```rust
if let Err(serenity::Error::Http(box serenity::http::error::Error::UnsuccessfulRequest(serenity::http::error::ErrorResponse { error: serenity::http::error::DiscordJsonError { code: -1, .. }, .. }))) = channel_id.say(&ctx.http, "Example") {
    println!("The message we sent was invalid");
}
```

This is a _lot_ of code for a simple task.

Error handling would be more pleasant if the error message as well as the error type for this failure case were tweaked to be more intuitive.

**Comment by CalliEve** [comment]
I would like to work on this by adding some methods on http::error::Error to check for some common errors like this one, if that's alright?

**Comment by Erk-** [comment]
Sounds good, though it should be noted that hopefully this specific error will go away when serenity is updated to v8

**Comment by CalliEve** [comment]
Yeah true, then the error would be carrying a struct/enum/json value (I don't know how you are planning on implementing it) inside it instead of just a message string. Afaik though, checking if the error was a DiscordJsonError for example would stay the same, which is what I would be making now. I would also be interested in helping with making the error handling code for v8 when the time comes though 😄
