### ISSUE TITLE
`threadpool` should be re-exported for those who want to implement `Framework`

### ISSUE THREAD

**Issue by recapitalverb** [serenity-rs/serenity#928]
I think the title is self-explanatory.

```rust
use serenity::threadpool::ThreadPool; // or something of the sorts

impl Framework for MyFramework {
    fn dispatch(&mut self, mut ctx: Context, msg: Message, thread_pool: &ThreadPool) { ... }
}
```

**Comment by acdenisSK** [comment]
I would agree, but we are soon planning to merge the [`async`/`.await` PR](https://github.com/serenity-rs/serenity/pull/905) and make a release candidate for it. 

After the PR, using a threadpool explicitly won't be needed anymore as the tokio runtime will abstract that for us. [This makes the definition of the `Framework` trait simpler](https://github.com/acdenisSK/serenity/blob/await_next/src/framework/mod.rs#L98). Of course, there is now a new dependency, `async_trait`, that is required in order to implement the `Framework` trait. But as you have suggested in this issue, [we are re-exporting it from Serenity](https://github.com/acdenisSK/serenity/blob/await_next/src/lib.rs#L120) to ease usage.

Once the PR is merged, an implementation of `Framework` would look like this:
```rust
#[serenity::async_trait]
impl Framework for MyFramework {
    async fn dispatch(&self, ctx: Context, msg: Message) {
        ...
    }
}
```

I'm closing your issue to avoid creating unnecessary effort as the threadpool is going to be removed in the near future and there will be only one release remaining for the 0.8 series before Serenity will fully become asynchronous.

**Comment by recapitalverb** [comment]
Thanks a lot! I only opened this as I was not aware about Serenity's transition to async. Going to subscribe to the async/await PR now!
