### ISSUE TITLE
[docs question]: add tutorial for building basic bot

### ISSUE THREAD

**Issue by jsjoeio** [serenity-rs/serenity#981]
Hi there! 

First, thanks so much for writing and maintaining this library! 🙏🏼

I wrote a [tutorial](https://developers.facebook.com/blog/post/2020/09/30/build-discord-bot-with-rust-and-serenity/) which walks you through building a basic bot with one command and getting it working locally. It builds off one of the examples more or less. I was wondering if there might be a good place in the docs to add this if you're open to it?

If not, feel free to close this! 

Thanks in advance! 😃

**Comment by arqunis** [comment]
Hello.

I am grateful for your effort that went into creating the tutorial, but I have to decline its inclusion to the documentation. For those who wish to get up-and-running quickly, [the ping-pong bot](https://github.com/serenity-rs/serenity/blob/current/examples/e01_basic_ping_bot/src/main.rs) example works well. That isn't to say that the library couldn't benefit from a tutorial. We were contemplating on creating a "book" in a style similar to [Rust by Examples](https://doc.rust-lang.org/rust-by-example/index.html) a while ago, and there was even one in the making. However, the author of the book disappeared to concentrate on work instead, so the idea was dropped. We could start fresh, but I plan on rewriting Serenity in the near future for the better; writing tutorials would cause them to immediately become stale as users reading them would face challenges with old code of the library that is no longer supported. Once we have gotten the library in a stable position, we might consider making a book again.

You do not have to worry. Although my plans are big, they will have to wait as I want to approach them steadily. It doesn't help that I have been getting busy with school since start of the school year, so I don't have a lot of time to spare developing the library instead. If you feel it, you can continue creating guides for the library, at least for now.

Again, thanks for the effort!

**Comment by jsjoeio** [comment]
Totally makes sense - the examples work super well so I'm grateful you include them.

No worries at all. I'll keep an eye out if the examples book pops up in the future. Thanks for the quick reply and the explanation @acdenisSK ! 🙏🏼
